### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by alexkops** [scalacenter/scastie#100]
When I run
`(1 to 10).map(_ + "€")`

The output I get is 
`
Vector("1â¬", "2â¬", "3â¬", "4â¬", "5â¬", "6â¬", "7â¬", "8â¬", "9â¬", "10â¬"): collection.immutable.IndexedSeq[String]`

So there is something going wrong with the encoding.

**Comment by MasseGuillaume** [comment]
Thanks, I will take a look

**Comment by MasseGuillaume** [comment]
This was the culprit: https://github.com/scalacenter/scastie/pull/103/files#diff-7c95257a9556c52df73d0b8826badea6R67

Nice catch!

**Comment by MasseGuillaume** [comment]
Fixed and deployed: https://scastie.scala-lang.org/5488
