### ISSUE TITLE
Practica de Scala

### ISSUE THREAD

**Issue by grandtranfers** [scalacenter/scastie#1019]
### Describe the bug

ejercicios de Scala

### Scastie snippet link

https://scastie.scala-lang.org/ZX9WAs5CQASOrcLoNhoa9g

### To Reproduce

2. Click on '...'
3. See error
...

### Expected behavior

ok

### Version

Scastie website

**Comment by grandtranfers** [comment]
primer ejercicio

**Comment by bishabosha** [comment]
the snippet provided runs without issue, why did you report this as a bug?
