### ISSUE TITLE
serialize akka-remote data

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#108]
If we change any data model in Api.scala we need to restart the sbtRunner. Since we already serialize with upickle between the client and the server we could serialize with upickle between the sbt instances and the server.

http://doc.akka.io/docs/akka/2.4/scala/serialization.html#Customization

**Comment by MasseGuillaume** [comment]
related https://github.com/scalacenter/scastie/issues/189

**Comment by OlegYch** [comment]
obsolete
