### ISSUE TITLE
Recursive code does not work in 3.5

### ISSUE THREAD

**Issue by golangcyberdude** [scalacenter/scastie#1093]
### Describe the bug

Recursive code does not work in 3.5, works on 3.5.1 RC2 and 3.4.2.  Also 3.3.3 LTS doesn't work.

### Scastie snippet link

https://scastie.scala-lang.org/Uu01YEoZSGiNho2ApB7XRw

### To Reproduce

Try this code in scastie in 3.4.2, 3.5 and 3.5.1 RC2
```
def recurseOnList(fields: List[String]): List[String] =
  if fields.isEmpty then
    println(fields)
    return fields
  println("xx" + fields.head)
  recurseOnList(fields.drop(1))

recurseOnList(List("1", "2", "3", "4", "5"))
```

### Expected behavior

Expected output
xx1
xx2
xx3
xx4
xx5
List()

### Version

Scastie website

### What browsers are you seeing the problem on?

Chrome

**Comment by rochala** [comment]
Hey, firstly, thanks for reporting the issue.

It seems like this issue is no longer reproducible and everything is working as intended.
Can you check once again and confirm that this is the case ?

Other than that, the issue may have been in the load balancer or some other place.

**Comment by golangcyberdude** [comment]
Fixed!  All working now.  Thanks.

**Comment by SethTisue** [comment]
does someone have permission to close the ticket? I don't have rights in this repo
