### ISSUE TITLE
Scastie down

### ISSUE THREAD

**Issue by golangcyberdude** [scalacenter/scastie#1095]
### Describe the bug

Scastie has not compiled code for past several days

### Scastie snippet link

https://scastie.scala-lang.org/0c9X3YBYTsaKdhRTkurdIQ

### To Reproduce

Try even a println("foo")

This also not working in Firefox
https://scastie.scala-lang.org/ifBuWJB9RJuRdl3t9SNHoQ
`List("Hello", "World").mkString("", ", ", "!")`

scastie: Sending task to the server.
scastie: Closed.

Worksheet mode or not, 2.x or 3.x (multiple versions tried, nothing)
Previously saved snippets also not working

### Expected behavior

foo

### Version

Scastie website

**Comment by rochala** [comment]
I'm on it. Should be fixed today

**Comment by golangcyberdude** [comment]
initial tests good! Thanks!
