### ISSUE TITLE
Worksheet mode output moves around, overlaps code

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scastie#126]
If I go up a line to edit some declared before a line with worksheet output (type info), going back causes the printed type info to move over and overlap my code.

<img width="259" alt="screen shot 2017-03-01 at 5 11 49 pm" src="https://cloud.githubusercontent.com/assets/687163/23468915/62705026-fea2-11e6-9097-e7e2558da0cd.png">

**Comment by freddie-freeloader** [comment]
The same happens if I add an empty line right before an annotated line.

**Comment by MasseGuillaume** [comment]
This got fixed somehow. I cannot reproduce.
