### ISSUE TITLE
Saves on run unexpectedly

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scastie#127]
![save-bug](https://cloud.githubusercontent.com/assets/687163/23469476/01ad2f00-fea4-11e6-8681-b92a474cc72f.gif)

Scastie saves a snippet when I press run. If I keep pressing run, it keeps saving more and more snippets each time I press run.

**Comment by MasseGuillaume** [comment]
@heathermiller Nice bug report :).

**Comment by MasseGuillaume** [comment]
You will need to hard reload on the address bar: `Command + Shift + R`. I'm adding a ticket for asset taging.
