### ISSUE TITLE
Rename button "Libraries (Build)"

### ISSUE THREAD

**Issue by freddie-freeloader** [scalacenter/scastie#128]
Since the toggle for the worksheet mode can also be found there, it might make sense to rename the **Libraries (Build)** button to **Settings**.

**Comment by MasseGuillaume** [comment]
It was named Settings previously but it was not obvious you could add Dependencies there.

**Comment by freddie-freeloader** [comment]
Alright :smile: Maybe I would make sense to split this into two as soon as Scastie gets more options. I had a really hard time finding the worksheet mode option mentioned in the help.
