### ISSUE TITLE
Button for "Libraries (Build)" is misaligned

### ISSUE THREAD

**Issue by mb720** [scalacenter/scastie#136]
Hi!

I'm on Firefox 51.0.1 (32-bit) and this is how the buttons on the left side look to me:
![bug](http://i.imgur.com/ZpYBBBM.png)

On [Gitter](https://gitter.im/scalacenter/scastie?at=58bad2b221d548df2c8d4a7e) Guillaume Massé called it a bug.

Let me know if I can provide additional info.

**Comment by MasseGuillaume** [comment]
We changed the icon and its now aligned :)
