### ISSUE TITLE
Is There a Support for creating a Akka Server On Scastie console?

### ISSUE THREAD

**Issue by shankarshastri** [scalacenter/scastie#142]

**Comment by MasseGuillaume** [comment]
The server where the code is running is in an isolated environment.

You can run both a client and a server in Scastie.

**Comment by shankarshastri** [comment]
@MasseGuillaume I wanted to know how can I run REST API from scastie?

**Comment by MasseGuillaume** [comment]
No this is out of scope.

**Comment by MasseGuillaume** [comment]
Here is an example with Playframework: https://scastie.scala-lang.org/MasseGuillaume/62vmEr9XR0qDWwimrO3r2Q

**Comment by shankarshastri** [comment]
@MasseGuillaume Running The code Is not the problem, how can I access routes...
