### ISSUE TITLE
"javap support"

### ISSUE THREAD

**Issue by er1c** [scalacenter/scastie#143]
It would be extremely useful to create some snippets of code and see what the underlying javap output for the class files generated by the scala compiler

It's sometimes tedious to do this for local class files if they get compared to various paths/etc, but could be extremely useful for something like scastie.

**Comment by MasseGuillaume** [comment]
This is a really advanced feature. I would prefer not to add it to Scastie since it adds complexity. If settings path is the issue, the solution could be to create an sbt plugin and use it on your own computer.

However, it might be useful to share bugs with the compiler team.

**Comment by er1c** [comment]
@MasseGuillaume I didn't want to comment on how simple it would be...because I doubt it would be!  But I add it as a "request" because it would be a REALLY useful feature - especially as a teaching tool or easy ad-hoc checks.  Also to see if other people would also find it equally useful or not.
