### ISSUE TITLE
Library search results should default to latest non milestone/RC

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scastie#145]
When adding a dependecy on "scalameta"

<img width="447" alt="screen shot 2017-03-14 at 11 25 01" src="https://cloud.githubusercontent.com/assets/1408093/23896248/fb1440fc-08a8-11e7-8804-f9e034bf754b.png">

In the scaladex settings page for scalameta/scalameta, we checked

<img width="480" alt="screen shot 2017-03-14 at 11 26 05" src="https://cloud.githubusercontent.com/assets/1408093/23896278/0efeb1b0-08a9-11e7-9d0c-58b2187c45e6.png">

It would be nice if the default selected version was 1.6.0 instead of 2.0-M.

**Comment by travis032654** [comment]
Potentially relevant [file](https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/release/DefaultRelease.scala)
