### ISSUE TITLE
Upgrade to Scala.js-react 1.0.0

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#152]
https://github.com/japgolly/scalajs-react/blob/master/doc/USAGE.md#setup

**Comment by arminio** [comment]
I'll have a look at this one.

**Comment by arminio** [comment]
I have not had much chance to look into this until now. 
Sorry about the long delay.

**Comment by MasseGuillaume** [comment]
It's alright. take your time ;)

**Comment by arminio** [comment]
a good summary of changes in scalajs-react v1.0.0:
https://github.com/japgolly/scalajs-react/blob/master/doc/changelog/1.0.0.md
