### ISSUE TITLE
Can't click on library from select list

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scastie#159]
In latest Chrome + Safari on OSX.

<img width="519" alt="screen shot 2017-03-31 at 14 37 23" src="https://cloud.githubusercontent.com/assets/1408093/24550706/93d02a3a-161f-11e7-9172-113bd37e7eb1.png">

Nothing happens when I click on "config" from the list.

**Comment by MasseGuillaume** [comment]
This one is a special case. It's a java library. It fails to add because it does not have a scala 2.12 target. It should no be in the list in the first place.

**Comment by MasseGuillaume** [comment]
When I redeploy scaladex this should be available.
