### ISSUE TITLE
Make it possible to embed scastie in a webpage

### ISSUE THREAD

**Issue by smarter** [scalacenter/scastie#16]
With [tut](https://github.com/tpolecat/tut) we can embed code in documentaton with its output, but it would be even better if we could embed runnable code.

**Comment by MasseGuillaume** [comment]
@felixmulder suggested to inject the DOM via javascript and avoid iframe. It allows the user to style the editor.

**Comment by heathermiller** [comment]
👍 on this!

**Comment by MasseGuillaume** [comment]
Partially Done in: https://github.com/scalacenter/scastie/pull/47
I need to add target selection in the API: https://github.com/scalacenter/scastie/issues/51 should be trivial.
