### ISSUE TITLE
Clear button doesn't do anything (Add a new button ?)

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scastie#162]
Clicking the clear button doesn't do anything. The code isn't cleared.

**Comment by MasseGuillaume** [comment]
The clear button removes the annotations and close the console.

**Comment by heathermiller** [comment]
Then how do I clear the code? How do I go from a saved snippet to a fresh one without wrangling with URLs?

**Comment by MasseGuillaume** [comment]
You can click on the Scastie logo to clear the url.

**Comment by heathermiller** [comment]
Yeah might be a good idea to add a new button maybe? I dunno, it just wasn't obvious to me how to clear without completely reloading
