### ISSUE TITLE
Mac Cmd symbol

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scastie#17]
<img width="574" alt="screen shot 2017-01-24 at 10 14 22" src="https://cloud.githubusercontent.com/assets/1408093/22241182/9d976c66-e21e-11e6-95e8-6f480abbdd9a.png">

**Comment by MasseGuillaume** [comment]
I will use: `<span class="oi" data-glyph="command"></span>`

**Comment by olafurpg** [comment]
😍  <img width="96" alt="screen shot 2017-02-13 at 22 37 13" src="https://cloud.githubusercontent.com/assets/1408093/22904501/08393652-f23d-11e6-875f-ef35e690ce96.png">
