### ISSUE TITLE
Running same program twice trigger sbt reload

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scastie#18]
Steps to reproduce
1. set cats as dependency
1. write `import cats._`
1. run
1. wait 11s to reload sbt, as expected
1. run, without any change to settings or code
1. waith 10s to reload sbt, unexpected

**Comment by MasseGuillaume** [comment]
It's due to the port load balancing algorithm: #14

**Comment by olafurpg** [comment]
Aha, makes sense. I'll close this as a duplicate then.
