### ISSUE TITLE
URLs with build settings information.

### ISSUE THREAD

**Issue by nicolasstucki** [scalacenter/scastie#181]
It would be helpful to have URLs to scastie that have some settings info such as which target, scala version and possibly libraries.

**Comment by felixmulder** [comment]
Could you ping us when this is released? :)

**Comment by MasseGuillaume** [comment]
@felixmulder pong https://scastie.scala-lang.org/?target=dotty

**Comment by felixmulder** [comment]
amazing, thanks :)
