### ISSUE TITLE
run as non root in docker

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#19]

**Comment by larsrh** [comment]
This is more of a question, but it appears that filesystem operations are persistent. I tried writing some files and they're still there after running it again. I'm not sure whether that's the intended behaviour.

**Comment by larsrh** [comment]
Also I suggest tagging this with `security` because running as `root` inside a container is dangerous.

**Comment by MasseGuillaume** [comment]
@larsrh why is it dangerous ?

**Comment by larsrh** [comment]
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/user
http://blog.dscpl.com.au/2015/12/don-run-as-root-inside-of-docker.html
http://gbraad.nl/blog/non-root-user-inside-a-docker-container.html
https://groups.google.com/d/msg/docker-user/e9RkC4y-21E/DvleOQDiPTUJ

**Comment by larsrh** [comment]
From what I understand you're supposed to make an attack _less likely_, which is easiest if you run inside the container with the minimum amount of privileges possible. (I've now updated my claim from 'dangerous' to 'discouraged'.)
