### ISSUE TITLE
Download project

### ISSUE THREAD

**Issue by raboof** [scalacenter/scastie#191]
It'd be neat to have a button that downloads the scastie project as a .zip including `build.sbt`, `project/plugins.sbt` and something like `src/main/scala/Worksheet.scala`.

This way you can easily continue work that started in scastie into a local IDE.

**Comment by MasseGuillaume** [comment]
This is an excellent idea!

**Comment by raboof** [comment]
cool! looking forward to trying it

**Comment by MasseGuillaume** [comment]
Deploying soonish.
