### ISSUE TITLE
autocompletion / autocomplete / code completion

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#20]
via ensime run `ensimeConfig` and restart the server

**Comment by heathermiller** [comment]
I'm happy you're adding features like these, but I really think that the focus right now should be on stability, scaling, and making sure that scastie isn't buggy.

**Comment by heathermiller** [comment]
Just saying that I think we should deprioritize this todo until we know v0 is solid and reliable.

**Comment by MasseGuillaume** [comment]
This is part of a Google Summer of Code: http://scala-lang.org/gsoc/2017.html#auto-completion-and-type-information-in-scastie

**Comment by MasseGuillaume** [comment]
Dotty just merged Language Server Protocol: https://github.com/lampepfl/dotty/pull/2532

**Comment by MasseGuillaume** [comment]
d2c16bfb72a99ded947a0ca0cfc7d828d23affdb
