### ISSUE TITLE
Document thread/concurrency model of Scastie runtime

### ISSUE THREAD

**Issue by benhutchison** [scalacenter/scastie#205]
I was using Scastie to investigate concurrency behavior under Monix (https://github.com/benhutchison/TaskConcurrencyExperiment) and noticed that behavior of a code snippet differed between my laptop and the scastie runtime: locally the same program terminates OK but it hangs under scastie.

Ideally this would not happen. But if this isn't possible, scastie should document the thread/concurrency model used to run snippets with, so we can know what conclusions it is/is-not safe to draw from its behavior.

**Comment by MasseGuillaume** [comment]
Thank for reporting.

https://scastie.scala-lang.org/MasseGuillaume/39hiXUV8Qdy8e4SyI4gq2w

**Comment by MasseGuillaume** [comment]
I think we spoke at Scala Days and the issue was with the code that was running and not Scastie per see.
