### ISSUE TITLE
Order of saved snippets off

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scastie#211]
I'd expect that when I save a new snippet that it's the most recent snippet in the list. But it's not. It looks like snippets are ordered alphabetically by hash, which is really weird.

What would make more sense is to order them by most-recently-saved date. It would also be good to print the date with the snippet as well.

**Comment by MasseGuillaume** [comment]
Yup that make total sense :+1:

**Comment by MasseGuillaume** [comment]
This is where we do the ordering/rendering: https://github.com/scalacenter/scastie/blob/master/client/src/main/scala/com.olegych.scastie.client/components/CodeSnippets.scala#L132
We can add the date/timestamp to this model: https://github.com/scalacenter/scastie/blob/cb02c3a096dfaf7350128912d3bd085def990501/api/src/main/scala/com.olegych.scastie.api/ApiModels.scala#L32
Here we can find the date the file was saved: https://github.com/scalacenter/scastie/blob/cb02c3a096dfaf7350128912d3bd085def990501/balancer/src/main/scala/com.olegych.scastie.balancer/SnippetsContainer.scala#L155

**Comment by MasseGuillaume** [comment]
fixed in: https://github.com/scalacenter/scastie/pull/231
