### ISSUE TITLE
Save button disappears randomly

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scastie#213]
- I saved a snippet.
- Went back to the editor, edited it.
- While editing, the save button disappeared
- Select all + copy all code to the clipboard
- Refresh
- Save button reappears
- Changes are lost. So, I paste copied code back into editor.
- Press save

(This keeps happening to me. The save button is frequently gone)

**Comment by MasseGuillaume** [comment]
Haha, this saves button is a sneaky one. Thanks for reporting.
