### ISSUE TITLE
Save button not updating snippet. It's creating new snippet

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scastie#214]
When I try to save an already-saved snippet that I'm working on, rather than creating a new revision of the already-saved snippet, it just creates a brand new snippet.

Now my list of snippets is full of duplicates.

**Comment by MasseGuillaume** [comment]
Hum this is totally related to: https://github.com/scalacenter/scastie/issues/213

After pressing save you should see:
1) fork
if you are logged in: 2) update, 3) amend

**Comment by heathermiller** [comment]
This is on my own snippet. What I did:

- clicked new
- wrote some code
- clicked save
- verified that the snippet was in my list of snippets
- went back to the editor
- wrote some more code
- clicked save

Then it created a totally new snippet with a different hash. I had expected it to just make revision 1.

**Comment by heathermiller** [comment]
To summarize, I saw "save", not updated or amend
