### ISSUE TITLE
It's possible to save a snippet without being signed in

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scastie#215]
I just visited a snippet I saved in incognito mode, and the save button was visible again. I clicked it, and it saved the snippet without being logged in:

https://scastie.scala-lang.org/QIdvRvTJRZulAkqJTHtdtw

**Comment by MasseGuillaume** [comment]
This is the correct behavior. Users can save anonymously.

Similar to: 
https://gist.github.com/anonymous/da2b66ed5f264d7e8661d9d9b3b31e08
https://jsfiddle.net/L7qcrcob/

**Comment by heathermiller** [comment]
Ok – I wasn't aware. Sorry for the noise!
