### ISSUE TITLE
Dotty enums don't work - using wrong parser?

### ISSUE THREAD

**Issue by felixmulder** [scalacenter/scastie#217]
https://scastie.scala-lang.org/PMExng30RiKeKYtyKKYYug

**Comment by MasseGuillaume** [comment]
You have to turn off the worksheet mode. We use Scalameta's parsers to instrument the code. It looks like it's not up to date with the current Dotty parser. I'm opening an issue on Scalameta.

https://scastie.scala-lang.org/vD9gD4pXRoCnLkaomP0PVQ

```scala
object Test {

  enum Maybe[+T] {
    case Just[T](t: T)
    case Nope
  }

  def main(arg: Array[String]): Unit = {
    import Maybe._
    val x = Just(5)
     println(x)
  }
}
```

**Comment by MasseGuillaume** [comment]
https://github.com/scalameta/scalameta/issues/895

**Comment by felixmulder** [comment]
Can it be off by default when running Dotty for now?

**Comment by MasseGuillaume** [comment]
Sure, I can do that.

**Comment by smarter** [comment]
@MasseGuillaume Ping, people are trying dotty on scala-native and getting confused about features not working right now: https://www.reddit.com/r/scala/comments/6ef7dl/announcing_dotty_012rc1_a_major_step_towards/ Maybe we should remove scastie from the dotty announcement  (http://scala-lang.org/blog/2017/05/31/first-dotty-milestone-release.html) until it's working?

**Comment by DarkDimius** [comment]
Looks like it's fixed. Should this issue be closed?

**Comment by smarter** [comment]
Thanks for the quick fix @MasseGuillaume!
@DarkDimius the worksheet mode still needs to be fixed for Dotty, until then you need to wrap all your code in an object with a main method to run it
