### ISSUE TITLE
Scastie tries to update/amend a snippet without having saved first

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scastie#218]
I just clicked new, typed some code, and I see only the UI for amending an already saved snippet. I haven't saved my snippet yet – I'd like to – but I can't. 

Screenshot (note no save hash in URL):
<img width="1103" alt="screen shot 2017-05-26 at 11 20 26 am" src="https://cloud.githubusercontent.com/assets/687163/26488928/9758c718-4205-11e7-8b37-56ac01cc6238.png">

**Comment by OlegYch** [comment]
how about simplifying the ui a bit, and just saving as a new snippet (or new version of existing snippet) every time you 'run'
people seem to be confused about what exactly amend/update/fork do, and sometimes forget to save at all
