### ISSUE TITLE
No way to update snippets on mobile

### ISSUE THREAD

**Issue by Jasper-M** [scalacenter/scastie#220]
On mobile (Chrome) there is no way to update a snippet. Even when you "request desktop site" the `amend` and `update` buttons don't appear.

![18789192_10212782772102530_1996188375_o](https://cloud.githubusercontent.com/assets/3708353/26531920/65c66e58-43f4-11e7-839d-2ec5ffd0aa92.png)

**Comment by MasseGuillaume** [comment]
![save](https://user-images.githubusercontent.com/921490/30958176-9f97e6fe-a43c-11e7-9e1f-296de8c2301f.jpg)
![save2](https://user-images.githubusercontent.com/921490/30958177-9fd6cbda-a43c-11e7-8c5f-0728b7f92617.jpg)
