### ISSUE TITLE
ensime core implies GPLv3

### ISSUE THREAD

**Issue by fommil** [scalacenter/scastie#226]
You can't depend on `"org.ensime" %% "core" % "2.0.0-M1"` without releasing your entire application under the GPLv3.

We released `"api"` under the Apache 2.0 license so that you could use the scala code as a reference when connecting over the SWANKY (tcp) or JERKY (websockets) protocols.

I trust this was an innocent mistake.

**Comment by MasseGuillaume** [comment]
Oh, I'm really sorry about that. It's an honest mistake.

**Comment by fommil** [comment]
it's ok, most people don't pay attention to licenses :smile:

**Comment by dimart** [comment]
Wow, I wasn't even paying attention to those license icons, I'm sorry @fommil, now I know.

**Comment by fommil** [comment]
well I'd personally prefer that you used GPLv3 but I understand that Scala Center may not be happy with that. Google Summer of Code is perfectly fine with GPL.

**Comment by fommil** [comment]
if you're just wanting to read the `.ensime` file in scala, you can depend on `api` (Apache 2.0) and `s-express` (LGPL 3.0) which get you 99% of the way there with typeclass derivation.
