### ISSUE TITLE
Make the default code example for Dotty compile

### ISSUE THREAD

**Issue by smarter** [scalacenter/scastie#234]
http://www.scala-lang.org/blog/2017/05/31/first-dotty-milestone-release.html links to https://scastie.scala-lang.org/?target=dotty which by default contains:
```scala
List("Hello", "World").mkString("", ", ", "!")
```
And thus does not compile with Dotty because it's not wrapped in an object and Scastie worksheet mode is currently disabled for Dotty (https://github.com/scalacenter/scastie/issues/217). I see several ways to fix this:
- Change the default example for dotty to be wrapped in `object Test { def main ... }`
- When the workspace mode is off, automatically wrap user code in `object Test { def main ... }` before sending it to the compiler
- Change the scastie link http://www.scala-lang.org/blog/2017/05/31/first-dotty-milestone-release.html to point to a scastie url with dotty code that compiles

@MasseGuillaume Do you think you would have time to implement either the first or second solution now? Otherwise I'll make a PR to update the scastie announcement url to something that compiles with dotty.

/cc @DarkDimius

**Comment by jedesah** [comment]
:+1:

**Comment by MasseGuillaume** [comment]
I think the ultimate solution is to make sure scalameta evolve as fast as dotty.

**Comment by MasseGuillaume** [comment]
@smarter fixing this now. What should be the Dotty Hello World? Something with union type? Something else?

**Comment by MasseGuillaume** [comment]
This is what I have so far: https://github.com/MasseGuillaume/scastie/commit/31e971d4335e0df1ab720953e0868e1b1d03efcc#diff-9f221c9e51e393fab10b1785d0f813f6R265
