### ISSUE TITLE
Embed scastie in websites

### ISSUE THREAD

**Issue by fwbrasil** [scalacenter/scastie#238]
It'd be great if scastie provided something similar to Gitter's [Sidecar](https://sidecar.gitter.im/). For instance, [Quill](http://getquill.io)'s website could have a "Try me!" tab alongside "Open chat" that allows the user to interact with the library without having to close the documentation.

**Comment by hardvain** [comment]
👍

**Comment by hardvain** [comment]
I am willing to work on this. Any suggestions and pointers are helpful.

**Comment by MasseGuillaume** [comment]
@fwbrasil 
Totally a good idea. I think this is similar: https://github.com/scalacenter/scastie/issues/154

http://embed.ly/ seems like a nice tool for this too: https://medium.com/@otto.chrons/scalafiddle-comes-to-medium-b0b1962063a8

**Comment by MasseGuillaume** [comment]
Your help is more than welcome @hardvain. The embedded view is a lot of work, I think this is 2 weeks full-time. If you want to help, I would prefer you start with one of these: 
* https://github.com/scalacenter/scastie/issues/228
* https://github.com/scalacenter/scastie/issues/201
* https://github.com/scalacenter/scastie/issues/200
* https://github.com/scalacenter/scastie/issues/197
* https://github.com/scalacenter/scastie/issues/50

**Comment by MasseGuillaume** [comment]
TODO:
* [ ] rename com.olegych.scastie.client.ClientMain to scastie.ClientMain in Scala.js instrumentation
* [ ] remove Global such that multiple embedding can use Scala.js
* [ ] investigate how to isolate stylecheats (ShadowDom, css namepace, prefixing style, etc)
* [ ] allow code folding

**Comment by MasseGuillaume** [comment]
@fwbrasil 

Here is a preview of the embedding mode: https://codepen.io/MasseGuillaume/pen/oeKoee

Let me know what do you think.

**Comment by MasseGuillaume** [comment]
Here you go: https://github.com/scalacenter/scastie#how-do-i-embed-scastie
