### ISSUE TITLE
opening a new session reloads the previous snippet

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scastie#241]
I think the default behavior when I go to http://scastie.scala-lang.org should be to create a blank snippet.

Currently, each time I want to create a new snippet, I go to scastie, I click on “new” and then I confirm. That requires 3 actions.

**Comment by fsvehla** [comment]
I have to disagree here - I think that applications should be found in the state you leave them and I appreciate that Scastie works this way

**Comment by raboof** [comment]
hm I actually like that behavior, too.

Perhaps some parameter that makes sure the snippet is cleared would be cool, something like http://scastie.scala-lang.org?new or so?

**Comment by MasseGuillaume** [comment]
@raboof there is a New button

**Comment by MasseGuillaume** [comment]
@julienrf I'm not sure why you don't want to keep your old code. Would you mind if I close this issue?

**Comment by julienrf** [comment]
When I go to scastie.scala-lang.org I want to open a fresh REPL. In my case, I more often create a new snippet than I effectively reuse an old one, so for me it’s more effort. But it’s OK to close this issue.

**Comment by MasseGuillaume** [comment]
You can open a PR to add this feature as an option in your user profile.
