### ISSUE TITLE
show hints where requested even if editing has moved on

### ISSUE THREAD

**Issue by dimart** [scalacenter/scastie#248]
The completions should appear at the location where they were requested,
even if user's cursor jumped somewhere in the meantime

**Comment by rorygraves** [comment]
If the user continues other activity I think you should not display it at all.

**Comment by dimart** [comment]
@rorygraves agreed

**Comment by MasseGuillaume** [comment]
d2c16bfb72a99ded947a0ca0cfc7d828d23affdb
