### ISSUE TITLE
Add time submitted to tasks in the status page.

### ISSUE THREAD

**Issue by rorygraves** [scalacenter/scastie#249]
When clicking on the 'status icon' (the Tick Ok in the bottom left) - I can see runners with multiple outstanding tasks - implying they are hung - as well as clicking on the task to see the details it would be good to see the submission time.

**Comment by MasseGuillaume** [comment]
There is an issue where task completes but are not marked completed.

**Comment by MasseGuillaume** [comment]
solved: https://github.com/scalacenter/scastie/commit/9d4a015eddf951067c195f21c05e13d8b611282e
