### ISSUE TITLE
Scala.js output runs twice

### ISSUE THREAD

**Issue by Jasper-M** [scalacenter/scastie#253]
When running an already compiled and downloaded Scala.js program it gets executed two times.

On Ubuntu, in Google Chrome. In Scala.js mode, I have the following code:

```
println("hello world")
```

After clicking `Run` for the first time the javascript console shows:

```
== Loading Scala.js ==
== Loading Scala.js ==
== Running Scala.js ==
hello world
```

After running `clear()` in the console and then clicking `Run` a second time:

```
== Running Scala.js ==
hello world
== Running Scala.js ==
hello world
```

**Comment by vincenzobaz** [comment]
I cannot reproduce https://scastie.scala-lang.org/s6hzgGLnTGGQ9tyxQ48TLw
