### ISSUE TITLE
update dotty to 0.2.0-RC1

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#254]

**Comment by DarkDimius** [comment]
I'll ping you on this issue when we'll have our stealth release.

**Comment by DarkDimius** [comment]
@MasseGuillaume, nice ping. It's now both on maven and on our releases page https://github.com/lampepfl/dotty/releases

**Comment by MasseGuillaume** [comment]
@DarkDimius cool I'm on it

**Comment by MasseGuillaume** [comment]
@DarkDimius https://github.com/lampepfl/dotty/blob/master/docs/blog/_posts/2017-07-11-second-dotty-milestone-release.md this link is 404

**Comment by DarkDimius** [comment]
@MasseGuillaume, thanks for heads up. It will 404 before we merge the blog post in tomorrow.

**Comment by MasseGuillaume** [comment]
You are good to go: https://scastie.scala-lang.org/fTgM22EnQxKv8qqGTOodnQ
