### ISSUE TITLE
library searching problems

### ISSUE THREAD

**Issue by scalway** [scalacenter/scastie#255]
A searching library doesn't work when 'target:scala.js' is selected.

PS: don't know why but the only version of scalatags is 0.3.2 (current version is 0.6.5 https://index.scala-lang.org/lihaoyi/scalatags/scalatags). Why don't we use index.scala-lang.org?

**Comment by MasseGuillaume** [comment]
> A searching library doesn't work when 'target:scala.js' is selected.

Can you give me an example?

> PS: don't know why but the only version of scalatags is 0.3.2 (current version is 0.6.5 https://index.scala-lang.org/lihaoyi/scalatags/scalatags). Why don't we use index.scala-lang.org?

We do use scaladex.

If I go to https://index.scala-lang.org/lihaoyi/scalatags the default library is scalarx. I just changed it to scalatags, it's now correct with 0.6.5.

**Comment by MasseGuillaume** [comment]
oh I see there is no results at all. This should be a quick fix.

**Comment by MasseGuillaume** [comment]
I created https://github.com/scalacenter/scaladex/issues/455 to track the Scala.js target filtering.

**Comment by MasseGuillaume** [comment]
solved in https://github.com/scalacenter/scaladex/commit/ffa6a76aae9c2904846a142486526d787e185d25
