### ISSUE TITLE
'Failed to update' when trying to save a change to someones else snippet

### ISSUE THREAD

**Issue by OlegYch** [scalacenter/scastie#259]
eg open https://scastie.scala-lang.org/k1Kk4JPuTcSHKkkFRXVA3A , type something, hit ctrl-s - get a confusing 'failed to update' 
i know that one is supposed to use 'fork' in this case but it is non-obvious
i still suggest to remove 'fork' 'amend' etc and just save on every run
related https://github.com/scalacenter/scastie/issues/218

**Comment by MasseGuillaume** [comment]
This is the next thing on my list.
