### ISSUE TITLE
aggressive autocompletion

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#266]
It would help for discoverability to autocomplete on dot:

```
foo.
   ^ triggers autocompletion
```

This is how I do it in ScalaKata:
https://github.com/MasseGuillaume/ScalaKata2/blob/master/webapp/js/src/main/scala/com.scalakata/Main.scala#L41
https://github.com/MasseGuillaume/ScalaKata2/blob/master/webapp/js/src/main/scala/com.scalakata/Hint.scala#L108

**Comment by OlegAlexander** [comment]
First, thank you so much for creating Scastie! As a newcomer to Scala, I think it's wonderful for learning, especially when I'm on my phone! 

Currently, I have to enter the first letter after pressing dot before seeing autocompletion suggestions. Is there a way to show all the suggestions as soon as I press dot? If doing that makes too many calls to the server, would it be possible to show the suggestions on demand? For example, by pressing dot and then Alt + Enter?

Thank you and sorry to comment on a closed issue.

**Comment by rochala** [comment]
It seems that I can't reproduce it. It works as intended for me so autocompletions are automatically triggered on dot e.g:

https://github.com/scalacenter/scastie/assets/48657087/cebf7014-05a9-4132-bf3d-fea2b65f4af4

As of the other question completions can be triggered with `ctrl + space`

**Comment by OlegAlexander** [comment]
That's bizzare. I just tried entering the exact same code as in your video and it still doesn't work with just dot. I have to enter `x.a` to see `aaaa` and `asInstanceOf` suggestions. I tried this on Windows 11 in Chrome, Chrome incognito, and Edge. I also tried this on my iPhone in Chrome and Safari. The website is https://scastie.scala-lang.org/, right?
