### ISSUE TITLE
migrate to sbt 1.0

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#281]

**Comment by jiminhsieh** [comment]
I will try to give this a shot. However, I have one question about `extraLoggers`. 
Type signature of `extraLoggers`:
* In 0.13.x, it's `SettingKey[(Def.ScopedKey[_]) ⇒ Seq[AbstractLogger]]`.
* In 1.0.x, it's `SettingKey[(Def.ScopedKey[_]) ⇒ Seq[Appender]]`.

I have not so sure how to handle this well, but I am still working on it! The only example I found is [this snippet](https://github.com/lihaoyi/workbench/blob/v0.4.0/src/main/scala/workbench/WorkbenchBasePlugin.scala#L50-L75).

**Comment by MasseGuillaume** [comment]
Yup I think this is the way to go. It looks like you have all the information in 
[LoggingEvent](https://static.javadoc.io/log4j/log4j/1.2.17/org/apache/log4j/spi/LoggingEvent.html)

the sbtTrap may have changed between 0.13.X and 1.X.

**Comment by vi-kas** [comment]
Were you able to get it working? **_extraLoggers_** with as specified in 1.0.x ?

**Comment by jiminhsieh** [comment]
@vi-kas Thanks for your reminding me! I was a little busy earlier. I guess I finished most of the works. However, I didn't finish the part of `AbstractLogger`. If you want to work on this, I could step back. :) Since I still need more time.

**Comment by allanrenucci** [comment]
Starting with version 0.8.0, Dotty will only support sbt 1. So until this issue is fixed, I believe Scastie won't support latest Dotty versions

**Comment by jiminhsieh** [comment]
I meet the same situation of this [comment](https://gitter.im/sbt/sbt?at=5998e10ec101bc4e3a3779a0) at gitter. I also found this related to frontend, and I don't have much experience about that... If there is anyone wants to pick this ticket, please go ahead. I am afraid that I will delay someone want to try Dotty 0.8.0 through Scastie.

**Comment by smarter** [comment]
@OlegYch @sjrd If there's no plan to move to sbt 1 soon, would you mind removing the outdated Dotty from https://scastie.scala-lang.org/ ? I keep having to tell people to not use it because it's outdated, so it's doing more harm than good at this point.

**Comment by OlegYch** [comment]
i'll have a look at migration this weekend

**Comment by smarter** [comment]
Wow, thanks a lot @OlegYch !
