### ISSUE TITLE
Client scalability

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#309]
The client can crash with massive output:

* large strings (since we removed pprint) (fixed in https://github.com/scalacenter/scastie/commit/adce1ce900660733c7f0cfe14c9f5081f5b713b0#diff-74a75189b40d694f2adcce7a9b1d4f94)
* lots of println (ex: `while(true){ println)("foo") }` ) (#356)
* infinite loops in Scala.js (https://github.com/scalacenter/scastie/issues/376)
* ...

**Comment by MasseGuillaume** [comment]
@sjrd

do you have ideas on how we could provide a better user experience for infinite loops, etc in Scala.js?

The execution starts when we load the Scala.js script tag to the dom.

One idea I have is to use WebWorker since they have a `terminate` method. However, you would lose a lot of operations like dom manipulation.

**Comment by sjrd** [comment]
Nah, if you do an infinite loop in JS, you're on your own.

Of course you could try and instrument the generated JS (or the IR before emission) to include a timeout checker in loops and at the beginning of functions, that would throw a fatal exception or something. But that's pretty tricky.

Or you go the research way and you try and reuse https://github.com/plasma-umass/Stopify

**Comment by MasseGuillaume** [comment]
@sjrd thanks for your input. I think Stopify is the way to go!
