### ISSUE TITLE
Scastie: connection closed

### ISSUE THREAD

**Issue by PiiitrZ** [scalacenter/scastie#316]
Hello,

every time I run my scala code in scastie (https://scastie.scala-lang.org/) the console writes just this: 

scastie: Sending task to the server.
scastie: Connected. Waiting for sbt
scastie: Closed.

And there ends my code testing. It was fine last week. But now, I can't run the same code I could last week. Where could be the problem please? 

Thanks in advance,
Peter.

**Comment by MasseGuillaume** [comment]
Hi @PiiitrZ,

This is an issue on our side, thanks for letting me know. I'm taking a look at it.

**Comment by nartamonov** [comment]
Just encounter this issue. I think Scastie should report clean error message in such cases, when it can't connect to SBT for some reasons (for example, overloading).

**Comment by MasseGuillaume** [comment]
@nartamonov I totally agree, Scastie should be better at reporting it's current state.

When I implement this ticket: https://github.com/scalacenter/scastie/issues/270 it will be easier to display useful information.

**Comment by MasseGuillaume** [comment]
@nartamonov I totally agree, Scastie should be better at reporting it's current state.

When I implement this ticket: https://github.com/scalacenter/scastie/issues/270 it will be easier to display useful information.

**Comment by muscovitebob** [comment]
I'm getting this output for any scala script today folks.

**Comment by kyouko-taiga** [comment]
FYI, I have been encountering this issue for a couple of days now.
In case that could possibly matter I'm running macOS 13.6 and observed the problem with both Safari and Chrome.
