### ISSUE TITLE
doobie does not show up in the library search box

### ISSUE THREAD

**Issue by tpolecat** [scalacenter/scastie#317]

**Comment by MasseGuillaume** [comment]
Thanks for reporting!

There is something wrong in Scaladex: https://index.scala-lang.org/search?q=doobie&page=1
It only shows 2.10 JVM as supported version

We can see here https://index.scala-lang.org/artifacts/tpolecat/doobie
that the latest version supports both 2.12 and 2.11

From maven:
http://repo1.maven.org/maven2/org/tpolecat/
http://repo1.maven.org/maven2/org/tpolecat/doobie-core_2.10/
http://repo1.maven.org/maven2/org/tpolecat/doobie-core_2.11/
http://repo1.maven.org/maven2/org/tpolecat/doobie-core_2.12/

It's consistent with the artifact page above.

This is where we collect supported version. At the first look it seems correct.
https://github.com/scalacenter/scaladex/blob/1fca06ce622e6f91df2537f5b87e5e55671d8200/data/src/main/scala/ch.epfl.scala.index.data/project/ProjectConvert.scala#L498

**Comment by tpolecat** [comment]
Ugh, botched release attempt. Thanks.

**Comment by MasseGuillaume** [comment]
@tpolecat the bug is on our side. We are not showing 2.11 and 2.12 as supported Scala version on your project.

**Comment by tpolecat** [comment]
Oh, it seems like me. If you filter out milestone releases then the latest (0.4.3) only exists for 2.10 because my release got messed up. I need to do a 0.4.4 release for 2.11/12 now to avoid confusion.

**Comment by MasseGuillaume** [comment]
Yep, it's indeed a weird release pattern. Regardless of this mess, Scaladex should say 2.10, 2.11 and 2.12 are available. Then on Scastie, depending on the Scala version selected, it should select the correct Doobie version.

**Comment by MasseGuillaume** [comment]
This is correct now. Fixed via: https://github.com/scalacenter/scaladex/pull/519

https://index.scala-lang.org/artifacts/tpolecat/doobie
vs
http://repo1.maven.org/maven2/org/tpolecat/doobie-core_2.10/
http://repo1.maven.org/maven2/org/tpolecat/doobie-core_2.11/
http://repo1.maven.org/maven2/org/tpolecat/doobie-core_2.12/
