### ISSUE TITLE
can't logout

### ISSUE THREAD

**Issue by dimart** [scalacenter/scastie#318]
![](https://d26dzxoao6i3hh.cloudfront.net/items/0w0a070o01102N032v1E/Screen%20Recording%202017-08-15%20at%2006.25%20PM.gif)

**Comment by dimart** [comment]
and here's the console output:
![](https://d26dzxoao6i3hh.cloudfront.net/items/2c3z1z0O1l1R3E2A3Z3x/Image%202017-08-15%20at%206.31.07%20PM.png?v=bb1f9a3e)

**Comment by MasseGuillaume** [comment]
@dimart the gif is so fast, you must be a gamer with incredible actions per minutes!

**Comment by dimart** [comment]
@MasseGuillaume 😄 argh, don't know why it's so fast, I wasn't 😈

**Comment by MasseGuillaume** [comment]
Fixed now.
