### ISSUE TITLE
scastie.org is down 

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scastie#332]
nginx 502 bad gateway:

<img width="559" alt="screen shot 2017-09-06 at 4 39 51 pm" src="https://user-images.githubusercontent.com/161079/30139324-0ad94e66-9322-11e7-8d1a-5a181ab2968f.png">

reported by a user on #scala IRC

**Comment by MasseGuillaume** [comment]
Should be good now, It looks like the server/runners did not enough memory.
