### ISSUE TITLE
Scastie is down

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scastie#348]
"502 Bad Gateway / nginx"

reported by a user at https://twitter.com/manub/status/914876746515849216

**Comment by manub** [comment]
This seems fixed now. Thanks!

**Comment by MasseGuillaume** [comment]
We added upstart to make sure the service restart in case it's crash ;-)

**Comment by SethTisue** [comment]
Scastie is down at present

**Comment by MasseGuillaume** [comment]
@SethTisue I think it restarted automatically
