### ISSUE TITLE
Disabling Predef leads to some interesting behavior.

### ISSUE THREAD

**Issue by Jacoby6000** [scalacenter/scastie#357]
Using compiler flag `-Yno-predef` leads to scastie having errors relating to methods `locally` and `println` not being defined.  This leads me to believe people could provide their own implementations for the `locally` method, which might cause unexpected behavior.

Instead of scastie secretly inserting `locally` and `println`, maybe scastie should invoke the methods directly as `scala.Predef.locally` and `scala.Predef.println`.

**Comment by MasseGuillaume** [comment]
indeed, good catch!

**Comment by Jacoby6000** [comment]
@MasseGuillaume Theoretically i've created a test that should be sufficient... I can't run the tests locally however.  all tests fail with a timeout.
