### ISSUE TITLE
Make scastie build windows conform

### ISSUE THREAD

**Issue by DaniRey** [scalacenter/scastie#364]
Some Scastie components currently do not work under Windows. The following issues where found.

sbtRunner/reStart and ensimeRunner/reStart do fail with 

`java.lang.RuntimeException: CreateProcessW() failed, error: 2`

As a workaround one may replace line 130 in SbtProcess with
`        command = List("sbt.bat"),`

Another issue is, that the `pkill` executable doesn't exist under Windows. @MasseGuillaume suggests the following.

We can borrow this code: https://github.com/OlegYch/scastie/blob/master/renderer/src/main/scala/com/olegych/scastie/ProcessKiller.scala
and change this part: https://github.com/scalacenter/scastie/blob/master/utils/src/main/scala/com.olegych.scastie/util/NonBlockingProcessPkill.scala

There seem to be some additonal issues, as the system didn't work properly after workarounds for both issues where applied locally. Let's gather all Windows related build issues in this ticket.

**Comment by OlegYch** [comment]
i made some fixes so that at least it can run snippets now

**Comment by OlegYch** [comment]
killing seems to work too, so i'm going to close this @DaniRey

**Comment by DaniRey** [comment]
Thanks a lot for resolving this!
