### ISSUE TITLE
Use a Database

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#378]
Currently, everything is saved to disk. (snippets, akka-http-session, etc). It worked well to jump-start the project, but with the number of snippets increasing, this technique does not scale.

for example, 
it takes 1.6s to load my snippet: https://scastie.scala-lang.org/api/snippets/MasseGuillaume/KQkojJF7QqC9ShwGtNx7lw/1
it takes 2.5s to load my snippets list: https://scastie.scala-lang.org/api/user/snippets (requires login)

however anonymous snippets are fast:
it takes 30ms to load this snippet: https://scastie.scala-lang.org/api/snippets/zfO94eUZQSit62azv7kXYA

**Comment by MouslihAbdelhakim** [comment]
Hello @MasseGuillaume,

Is this issue a priority ? i would like to work on it, but i am open to work on any other issue with higher priority.

**Comment by MasseGuillaume** [comment]
@MouslihAbdelhakim I think https://github.com/scalacenter/scastie/issues/50 would be pretty cool.

**Comment by MouslihAbdelhakim** [comment]
@MasseGuillaume that was the first issue i looked at, but i'm hesitated to tackle it. Because i have no prior experience with front end technologies (JavaScript,HTML or Scala JS) and Scala native.

Do you think prior experience with these technologies is required?

**Comment by MasseGuillaume** [comment]
@MouslihAbdelhakim the difficulty of #50 is to get play-json work on native. You can start by trying to compile a scala-native project on your computer for example.

**Comment by MouslihAbdelhakim** [comment]
@MasseGuillaume  i will this issue while looking into #50 on the side.

Do you have a preference on which Database and library to use?

**Comment by MasseGuillaume** [comment]
@MouslihAbdelhakim I think https://github.com/getquill/quill is pretty good. And flyway for migration: https://flywaydb.org/documentation/plugins/sbt

**Comment by MouslihAbdelhakim** [comment]
Hello @MasseGuillaume Quill and cassandra ?  since most the data is structured as  a one (the user) to many (snippets...) relationship we don't need an RDBMS.

**Comment by MasseGuillaume** [comment]
@MouslihAbdelhakim you have a good point we don't need an RDBMS. What about mongodb, it's already running on our server and we can use play-json to serialize/deserialize. It's also already available in our codebase.

**Comment by MouslihAbdelhakim** [comment]
@MasseGuillaume i would prefer Quill+Cassandra because of Quill's , but if introducing a new database dependency will make the IT administration side more complexe then we can go with mongoDB.

Which driver/ library is present in the scastie code base? and which mongoDB version should we use?
