### ISSUE TITLE
Support for Scala.js

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#38]
Vote with a :+1: on this issue.

**Comment by bskern** [comment]
👍

**Comment by wang7x** [comment]
👍

**Comment by pepyakin** [comment]
has to say, that is voting for posts are available only on desktop version

**Comment by ekrich** [comment]
+1

**Comment by rolisv** [comment]
👍

**Comment by pawank** [comment]
👍

**Comment by thorbenlouw** [comment]
👍

**Comment by lrlucena** [comment]
👍

**Comment by er1c** [comment]
👍

**Comment by MasseGuillaume** [comment]
Let's do it!

**Comment by arminio** [comment]
👍

**Comment by shankarshastri** [comment]
:+

**Comment by MasseGuillaume** [comment]
status:

* [x] show instrumentation
* [ ] attach dom elements
* [ ] display runtime errors (exceptions with stacktrace)

**Comment by MasseGuillaume** [comment]
![raycasting](http://i.imgur.com/JD6LOCA.png)

**Comment by MasseGuillaume** [comment]
Guys, you asked for it and we delivered!

Scastie is now so dodge, such wow
https://github.com/scalacenter/scastie/blob/master/demo/dodge.scala

You can also run, the crazy raycasting demo from @lihaoyi
https://github.com/scalacenter/scastie/blob/master/demo/raycasting-scalajs.scala

There is a known issue with sharing: https://github.com/scalacenter/scastie/issues/149. We are working on it right now.

Have fun!
