### ISSUE TITLE
sbt routing seems suboptimal

### ISSUE THREAD

**Issue by OlegYch** [scalacenter/scastie#382]
run two scasties -  one with default config, the other with eg scala 2.11
observe 'sbt runners' to have two distinct configs
run the scastie with default config a few times - there is about 1 in 5 chance that it will run using sbt with different config
run the other scastie - there is almost 100% chance that it will trigger a reload and needlessly create one more sbt runner with same config, this will repeat until all runners will have 'same configuration'

so essentially it looks like routing is random, with no preference to use runner with same config

**Comment by MasseGuillaume** [comment]
We only keep one configuration per IP:
https://github.com/scalacenter/scastie/blob/master/balancer/src/main/scala/com.olegych.scastie.balancer/LoadBalancer.scala#L25

If you have ip1 and set a runner to c2 (all other runners are on c1 by default) when you switch back to c1 there is no guarantee that we will keep c2 (it is discarded from the history). Maybe we could allow 2 configurations per ip. This would improve the scenario you describe above.

**Comment by OlegYch** [comment]
i don't think this is related to per-ip limit (although it too sounds problematic) 
in the situation above the same config is not being reused most of the time
you can even reproduce it with one config - just keep running the same snippet and there is about 30% chance that you'll encounter a reload, even though all sbt runners report 'same configuration'

**Comment by MasseGuillaume** [comment]
You are right: I just tested and I got the following output:

state 0:
c0: 6

run c1

state 1:
c1: 1
c0: 6

run c1

state 2:
c1: 2
c0: 4

run c1

state 3:
c1: 2
c0: 4

run c1

state 4:
c1: 3
c0: 3

run c1

state 5:
c1: 3
c0: 3

...

**Comment by OlegYch** [comment]
@MasseGuillaume are you going to do anything about it?

**Comment by MasseGuillaume** [comment]
I'm on it.

**Comment by MasseGuillaume** [comment]
I cannot reproduce it: https://github.com/MasseGuillaume/scastie/commit/074a697a5be2bce84d8c0d38acb814f766f15806#diff-6b0b8d9abc4596cb28f4b0e437bcaa02R9

I also ran the scenario above on the website and it picked the same server all the time. Let's keep an eye on this. If you can give me another failing scenario I can try again.

**Comment by OlegYch** [comment]
ok i'll try

**Comment by OlegYch** [comment]
seems fixed with recent routing changes
