### ISSUE TITLE
Communication prematurely closed

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scastie#387]
This is what I got when I tried to run my program:

![image](https://user-images.githubusercontent.com/332812/36248230-090e2a90-1237-11e8-9f1c-b839d6926873.png)

**Comment by MasseGuillaume** [comment]
What is the input?

**Comment by julienrf** [comment]
~~~ scala
import strawman.collection.immutable.{ LazyList, List }

lazy val fib: LazyList[Int] = 1 #:: 1 #:: (fib zip fib.tail).map { case (x, y) => x + y })

fib.take(10).to(List)
~~~

**Comment by MasseGuillaume** [comment]
scalaVersion ?

**Comment by julienrf** [comment]
2.12

**Comment by OlegYch** [comment]
the code was unparsable, i think i fixed handling failure to parse
(we parse the code before submitting it to sbt to insert worksheet instrumentation)
