### ISSUE TITLE
very slow loading (occasionally)

### ISSUE THREAD

**Issue by OlegYch** [scalacenter/scastie#391]
about half the time loading a snippet takes >10 seconds
combined with no loading indication it is very confusing
eg https://scastie.scala-lang.org/k3u2cmfUTUyCBqh3EaSMbQ
![x0_udow3rkci-krbhnnmpw 1](https://user-images.githubusercontent.com/268312/37033802-3b533092-2158-11e8-842d-e44fbde4bad0.png)

**Comment by MasseGuillaume** [comment]
It's related to this: https://github.com/scalacenter/scastie/issues/378

The snippets are stored on a network disk and this is super slow. An easy fix would be to store them in MongoDB.

**Comment by OlegYch** [comment]
it's on NFS?

**Comment by MasseGuillaume** [comment]
It's on PotatoFS. I will talk with the sysadmin in a few minute, this morning he freed some disk space.

**Comment by MasseGuillaume** [comment]
@OlegYch It's on NFS. Apparently, there are more than 500 000 snippets and this corresponds to 33GB of disk space. Every time you run, the snippet is saved to disk. If you compile Scala.js each run is 1MB, otherwise, it's ~1KB.

This is my next priority, I will take a look at in ~2 weeks.

**Comment by OlegYch** [comment]
thanks!
not sure why the amount of snippets matters, but not surprised that NFS is behaving wonky
