### ISSUE TITLE
Autocomplete duplicates text on Samsung Internet

### ISSUE THREAD

**Issue by Woodz** [scalacenter/scastie#395]
Using Android 7 with Samsung Internet 6.4.10.5 gives very annoying behaviour where code would be randomly duplicated whilst typing (see screenshot). This appears to happen for the 2nd character typed after a full stop.
![screenshot_20180418-185120](https://user-images.githubusercontent.com/966157/38927873-a1bc8cd8-42f6-11e8-9afc-225ceef28a2f.png)

**Comment by OlegYch** [comment]
@Woodz can you try now and see if it's still an issue?
