### ISSUE TITLE
Seems a error at scastie.scala-lang.org!

### ISSUE THREAD

**Issue by QuestionPython** [scalacenter/scastie#397]
Link :
https://scastie.scala-lang.org/IVLD6XOBSrWYmjfjNSwnfQ

Code :
--------
```
print("hello")
```

after press `Run` , its show :
```
hello[{"position":{"start":0,"end":14},"render":{"v":"()","className":"Unit","$type":"Value"}}]
```

what they?! (`[{"position":{"start":0,"end":14},"render":{"v":"()","className":"Unit","$type":"Value"}}]`)
its a json , may be for `code highlighting` using html,css

**Comment by MasseGuillaume** [comment]
Hey, in Scala `println` is the equivalent of Python's `print`. In Scastie you can write the expression directly to see it's result. Try only writing an expression (ex: 1 + 1). `print` in Scala is equivalent to `sys.stdout.write` in Python.

Regarding the JSON code you see, this is indeed a bug, `print` should behave like `println`.

**Comment by OlegYch** [comment]
fixed
