### ISSUE TITLE
Can't run code on Scastie.

### ISSUE THREAD

**Issue by RaviBJadhav** [scalacenter/scastie#398]
I am trying to run simple code on the scastie but seems the Run button is disabled. Could you please let me know how to make it enabled or is there any setting to be set prior running any code on it.
I am new to scastie.

Thanks,
Ravi Jadhav.
![scastieissue](https://user-images.githubusercontent.com/38745052/39286506-f957136e-493b-11e8-8f1c-8dcfa8e96d14.png)

**Comment by asarkar** [comment]
Same issue.

**Comment by rintcius** [comment]
I'm also running into this issue, but only every now and then. Most of the time it does work for me.

**Comment by OlegYch** [comment]
@rintcius when did you last run into it?

**Comment by rintcius** [comment]
@OlegYch just before I reported it

**Comment by OlegYch** [comment]
hm ok, i'm keeping an eye on it

**Comment by kolheanup** [comment]
I am facing the same issue now

**Comment by OlegYch** [comment]
thanks, looks like getting status times out but running still works
will investigate

**Comment by OlegYch** [comment]
running via ctrl-enter that is, even though run button is disabled

**Comment by OlegYch** [comment]
fixed

**Comment by vijayramaraju123** [comment]
try with Alt+Enter to run the code
