### ISSUE TITLE
Share code without automatic run

### ISSUE THREAD

**Issue by raja-s** [scalacenter/scastie#399]
This is not a major suggestion, but it would be nice to have an option with a snippet share URL that has, say a parameter in the query string that prevents Scastie from immediately running the code on page load. Sometimes I just want to share an incomplete snippet with someone ([example](https://scastie.scala-lang.org/raja-s/G18bN28fQfu2Km0Nlgf6GQ/3)) without them having plenty of errors and warnings blowing up in their face. Yes, if the person I'm sharing the snippet with is familiar with Scastie, they can just press `esc`, but not everyone is ;)

**Comment by MasseGuillaume** [comment]
This is a good suggestion. A workaround would be to add placeholders `???`.

```scala
// Incomplete code demo
def example(list: List[Int]): Int = list match {
  case Nil          => ??? /* Return something here */
  case head :: tail => ??? /* Return something else */
}
```

**Comment by raja-s** [comment]
Oh right, I forgot about those :p still, it might be useful in cases where for example you introduce dummy variables/types whose names describe their purpose and just assume they were defined elsewhere in the code.

**Comment by OlegYch** [comment]
what if 'Clear annotations' is renamed to 'Hide errors' so it's a bit more clear for a novice?
i'd rather not encourage usage as a plain pastebin

**Comment by raja-s** [comment]
Good point! I myself did not immediately understand what that button does, until I clicked it...

**Comment by raja-s** [comment]
It is a particularly good suggestion also because the term "annotation" in Scala/Java refers to the @ annotations, so the current text in the button is a little bit confusing to be honest.
