### ISSUE TITLE
Want to use com.twitter.util as library but cannot find it from search bar

### ISSUE THREAD

**Issue by YikSanChan** [scalacenter/scastie#400]
I want to use library `com.twitter.util` but failed to find it from "Build Settings" -> "Libraries" search bar.

Is there any way I can import this?

**Comment by heathermiller** [comment]
Yeah, sometimes the dropdown search isn't amazing. 

However, you can just add `com.twitter.util` to your sbt configuration. If you just click "build settings" on the left-hand side, and then add the following line to the end of your sbt configuration, you should be set:

```scala
libraryDependencies += "com.twitter" %% "util" % "7.0.0"
```

This is a general rule, by the way. You can always just add dependencies that you know are out there on maven by putting them into the sbt configuration as usual (as if you were running on your own machine)

**Comment by heathermiller** [comment]
Closing this because I just checked that this should all work out fine if you add it manually to the sbt configuration in UI. Reopen if I've misunderstood :)

**Comment by YikSanChan** [comment]
Thank you, it solved the problem! 

Shall we put it in help, so that people knows what to do when search bar doesn't work? (Personally, I come from a job that doesn't need to care about sbt itself, so I fail to figure out what to do...) Link like this would be helpful: [sbt example](https://alvinalexander.com/scala/sbt-syntax-examples)

**Comment by YikSanChan** [comment]
As a supplement, my final sbt configuration is:
```
scalacOptions ++= Seq(
  "-deprecation",
  "-encoding", "UTF-8",
  "-feature",
  "-unchecked"
)

libraryDependencies ++= Seq(
  "com.twitter" % "util-core_2.12" % "18.4.0"
)
```

Maven repo: http://search.maven.org/#artifactdetails%7Ccom.twitter%7Cutil-core_2.12%7C18.4.0%7C

**Comment by YikSanChan** [comment]
Oops, duplicate of #82

**Comment by stratigos** [comment]
Thanks, this really helped me figure out what the correct module or artifact names are for `twitter.util` :+1:
