### ISSUE TITLE
Sbt configuration fail to render from a link with snippet id

### ISSUE THREAD

**Issue by YikSanChan** [scalacenter/scastie#402]
If start from a link without id: https://scastie.scala-lang.org/, Sbt configuration is rendered:
![image](https://user-images.githubusercontent.com/17229109/39665597-e60ebd0e-504b-11e8-9943-581837fc2387.png)
However, when start from a link with id: https://scastie.scala-lang.org/YikSanChan/d4anSLyNQvyj1KhxSq95gQ, Sbt configuration is empty at first:
![image](https://user-images.githubusercontent.com/17229109/39665612-0052d592-504c-11e8-9775-dba7c61930a2.png)
To see sbt configuration, I need to manually search and add a library:
![image](https://user-images.githubusercontent.com/17229109/39665617-1c9f2f20-504c-11e8-8709-5567d054476a.png)

**Comment by OlegYch** [comment]
should be fixed bow
