### ISSUE TITLE
Replace scastie library search with scaladex library search

### ISSUE THREAD

**Issue by ShaneDelmore** [scalacenter/scastie#403]
Scastie library search much worse than scaladex search, it would be nice to integrate the two projects a bit and leverage scaladex for library search and scastie for trying out the libraries found.

For examples of searches I was unable to make work, try searching for twitter/util-collections.  Or finagle-http, or twitter/util-zk, or twitter/util.

It would also be handy if the search matched on exact package name or path in package, as in if i know I want to try out code in com.twitter.util, it would be great if I could just search for com.twitter.util and see the libraries that supply it directly.

**Comment by OlegYch** [comment]
it's already using scaladex, search quality issues are handled there
