### ISSUE TITLE
Dotty compiler reporter does not report the line position

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#41]
TODO: https://github.com/lampepfl/dotty/pull/1884

**Comment by ennru** [comment]
The shell colors in Dotty's error messages should either be supported, or switched off.
e.g. `|[31m'{'[0m expected, but [31m'}'[0m found` is not very readable

**Comment by MasseGuillaume** [comment]
@ennru totally: https://github.com/scalacenter/scastie/issues/186

**Comment by OlegYch** [comment]
fixed now
