### ISSUE TITLE
Error to add scala.actors

### ISSUE THREAD

**Issue by jairoteran6** [scalacenter/scastie#421]
![image](https://user-images.githubusercontent.com/18144984/46963638-cdf0f980-d06b-11e8-846c-61e262d95c05.png)

**Comment by adelescott** [comment]
I also am having the same error when trying to add scala / parser-combinators. To work around I entered it manually in the sbt configuration:

```libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "1.1.1"```

**Comment by OlegYch** [comment]
@adelescott 
looks like current scala version is missing on scaladex, i created an issue https://github.com/scalacenter/scaladex/issues/560
