### ISSUE TITLE
No version choose for the first chosen library

### ISSUE THREAD

**Issue by Odomontois** [scalacenter/scastie#427]
Whenever you choose library via search, dropdown of the first one shows only the default version, dropdowns of second and others however are ok.

![default](https://user-images.githubusercontent.com/247558/51443281-79f35200-1cf7-11e9-8842-aa3f11f19e8a.png)

![default](https://user-images.githubusercontent.com/247558/51443285-85467d80-1cf7-11e9-9c08-e248e66a56cf.png)

**Comment by OlegYch** [comment]
should be fixed now
