### ISSUE TITLE
Dotty compiler errors are not inserted at the correct source code lines

### ISSUE THREAD

**Issue by Sciss** [scalacenter/scastie#430]
As seen in Firefox 60.5.0esr:

https://scastie.scala-lang.org/aIw4sn6zTUKsUDfeOCH0tw

The errors are all pasted towards the top of the source code instead.

![screenshot from 2019-02-07 12-36-19](https://user-images.githubusercontent.com/131300/52411462-43ca1680-2adc-11e9-944d-6be5623c745e.png)

**Comment by OlegYch** [comment]
caused by #41 , probably requires dotty and sbt upgrade
