### ISSUE TITLE
Update Dotty implied to delegate

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scalacenter/scastie#438]
When selecting Dotty 0.16.0-RC3 in the settings, I sometimes get the following code by default as an example:

```scala
def f(x: Int)(z: Int)given (y: Int) = y
implied for Int = 10
object Foo extends App { println(f(1)(2)) }
```

The RC3 change renamed `implied` to `delegate`, so the correct version is now:

```scala
def f(x: Int)(z: Int) given (y: Int) = y
delegate for Int = 10
object Foo extends App { println(f(1)(2)) }
```

I can't find that snippet in code though, so I can't submit a PR.

**Comment by anatoliykmetyuk** [comment]
Is it a caching problem by chance?

**Comment by OlegYch** [comment]
@anatoliykmetyuk yep the last snippet is kept in local storage
