### ISSUE TITLE
Insert two spaces instead of a tabulation when the tab key is pressed

### ISSUE THREAD

**Issue by smarter** [scalacenter/scastie#444]
The default in most editors is that pressing tabs enter spaces, but this isn't the case in Scastie. Besides the fact that this can easily lead to mixed tabs/spaces in copy-pasted code, it can lead to errors in recent versions of Dotty which experiment with indentation-based syntax (see https://contributors.scala-lang.org/t/significant-indentation-mixing-tabs-and-spaces/3648/3?u=smarter).

**Comment by OlegYch** [comment]
unfortunately this doesn't look well supported atm in codemirror https://discuss.codemirror.net/t/indentation-with-space-in-codemirror/1835

**Comment by smarter** [comment]
Thanks!
