### ISSUE TITLE
Dotty: trivial snippet fails due to "Expected a toplevel definition"

### ISSUE THREAD

**Issue by ryanberckmans** [scalacenter/scastie#446]
https://scastie.scala-lang.org/hQRmWshCQeiGirP0cs1JgA using dotty 0.18.1-RC1

Follow up from https://github.com/lampepfl/dotty/issues/7221

**Comment by OlegYch** [comment]
this only works in 2.13 due to worksheet mode, which is not available for dotty atm

**Comment by francisdb** [comment]
workaround:

```scala
@main def main = {
  // put your code here
}
```

**Comment by vincenzobaz** [comment]
Worksheet mode is now supported for Scala 3 snippets too
