### ISSUE TITLE
Assigning an async DB resolution to a shared val is not recommended

### ISSUE THREAD

**Issue by cchantep** [scalacenter/scastie#455]
https://github.com/scalacenter/scastie/blob/10df30581e12c0def6f2374f60054eb56677f30e/storage/src/main/scala/com.olegych.scastie.storage/MongoDBSnippetsContainer.scala#L59

Also it would be better to avoid shadowing: https://github.com/scalacenter/scastie/blob/10df30581e12c0def6f2374f60054eb56677f30e/storage/src/main/scala/com.olegych.scastie.storage/MongoDBSnippetsContainer.scala#L71

**Comment by OlegYch** [comment]
thanks, would you recommend doing it on each request then?

**Comment by OlegYch** [comment]
@cchantep does this look good? https://github.com/scalacenter/scastie/commit/61190531fc860aced7d0acdd26a5d5471f1362ee
