### ISSUE TITLE
Saved worksheets for how long? 

### ISSUE THREAD

**Issue by jdreyesp** [scalacenter/scastie#462]
This issue has more a question shape: how long does a worksheet 'lives' before is wiped out from the server? In case we want to prepare something 'complex', we don't want to lose work when the worksheet is wiped out. 

This is also related with https://github.com/scalacenter/scastie/issues/461 . If I have this functionality, I can upload the project again and then don't lose work done.

**Comment by OlegYch** [comment]
they live as long as scalacenter doesn't run out of storage, ie there is no planned expiration
some old snippets may fail be reevaluated due to sbt/plugins updates (notably scala.js and dotty), but the original output is stored forever
