### ISSUE TITLE
Add scalajs 1.0 to targets

### ISSUE THREAD

**Issue by er1c** [scalacenter/scastie#466]
For the targets, I would like to see Scala.js broken out into `Scala.js 0.6` and another `Scala.js 1.0`

So I can specify either: 

Scala Version: 0.6.32 on Scala 2.13.2

-or-

Scala Version: 1.0.1 on Scala 2.13.2

Thanks!

**Comment by OlegYch** [comment]
hey @er1c , perhaps you could help me out
i've started updating to 1.0 but not sure what's happening here https://github.com/scalacenter/scastie/blob/scalajs1/client/src/main/resources/dev-common.js#L1
the `$e` variable seems to be gone

**Comment by OlegYch** [comment]
nvm this seems to be solved

**Comment by OlegYch** [comment]
@er1c is supporting 0.6 really worth it at this point? crossbuilding gets pretty complicated

**Comment by er1c** [comment]
@olafurpg I think 1.0 is better, I can't say all of my projects are 0.6 yet, but that's not usually where I'm prototyping.   Scastie is great for showing bug reports, and 1.0 support would help further "active" development.

**Comment by OlegYch** [comment]
updated to scala.js 1.1.0

**Comment by OlegYch** [comment]
somthing is wrong with optimized client build, reopening

**Comment by OlegYch** [comment]
updating to 1.1.1 fixed it
