### ISSUE TITLE
Code using `ParArray` is timing out.

### ISSUE THREAD

**Issue by leobenkel** [scalacenter/scastie#474]
When using `par` , the code never finish

Using scala 2.12 https://scastie.scala-lang.org/uIwG8gCRQCaEUy1QbwgChg
Using scala 2.13 https://scastie.scala-lang.org/xpwC3IC5TAWpckLxEzHRjg

At first i tried with `sum` instead of `reduce`. I just wanted to experiment. 

I also tried with `.seq` before the `sum`. 

It works with `foldLeft` but we loose the parallelization doing so. 

and `sum` on its own works as well. 
But not with the `map` first. 

`aggregate` does work. 

oh ! After more investigation, it seems like it is working without the `increment` function: 
https://scastie.scala-lang.org/0pTTjfMETCeYUAjW2YwQIw

**Comment by OlegYch** [comment]
thanks for the report
this is probably related to https://github.com/scala/bug/issues/8119 and is triggered by worksheet mode
the code works fine with worksheet mode off https://scastie.scala-lang.org/2rOwdNPITgm6qXNOcYqxRw

**Comment by leobenkel** [comment]
ah ok, thank you @OlegYch !
