### ISSUE TITLE
Add withDottyCompat to dependency list

### ISSUE THREAD

**Issue by DieBauer** [scalacenter/scastie#478]
Having Scastie with dotty, and a library that isn't cross-published, I would like to see the withDottyCompat flag available for these dependencies.

**Comment by julienrf** [comment]
You can already use `withDottyCompat` if you write your dependencies manually. See the build settings of this https://scastie.scala-lang.org/GYlLDDeJSmmonjWzMbfBVg

Is this an acceptable solution for you?

**Comment by DieBauer** [comment]
I was not aware of this feature! Yes this is acceptable. I used the `Libraries` search field to find a dependency and then it gets added automatically in the non-editable sbt config, but adding it manually to extra config is indeed working.

**Comment by julienrf** [comment]
Cool, then I’m closing this issue :)

I guess `withDottyCompat` will soon be handled automatically by sbt so this is a temporary situation anyway.
