### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by markblokpoel** [scalacenter/scastie#479]
Most keyboard shortcuts are not working, only CTRL-Enter works. Auto-completion doesn't, nor any of the other shortcuts. Tried with empty worksheet in Chrome, Edge and Brave (latest versions today).

**Comment by OlegYch** [comment]
which shortcut do you mean in particular?
scastie editor supports most sublime shortcuts
there is no auto-completion atm

**Comment by markblokpoel** [comment]
Thanks for the quick reply! I was mostly trying auto complete and line selection, both I think don't work. So its actually a subset of the sublime commands that are implemented. I understand now. Maybe the help menu can reflect that 'most' shortcuts work? Easy fix to prevent expectation mismatch. :)

I ask this fully aware of the monumental task implementing auto completion is... But is auto-completion something that is on the dev roadmap? I would like to use scastie in an interactive book on programming simulations in scala. For new learners auto-completion might be an invaluable tool.

**Comment by OlegYch** [comment]
@markblokpoel unfortunately autocomplete is not on roadmap right now, you can try http://scalafiddle.io/ which has it
