### ISSUE TITLE
Dotty vs. Scala 3

### ISSUE THREAD

**Issue by b-studios** [scalacenter/scastie#486]
Currently, the language selection menu offers a separate choice for "Dotty". With the release of the milestones under the name "Scala 3-M?" it would make sense to (at least) rename "Dotty" to "Scala 3" if not even merge it with the language selection of "Scala 2".

**Comment by vincenzobaz** [comment]
#488 uses the `Scala 3` naming instead of `Dotty`. I think similarly to scala docs, we should keep versions 2 and 3 separated.
