### ISSUE TITLE
scastie Format fails for inline match

### ISSUE THREAD

**Issue by jasonmar** [scalacenter/scastie#511]
Running Format in scastie on the Scala 3 example below fails and prints a "Formatting failed" error. The code compiles and runs fine, it looks like this could be fixed by updating the scalafmt version to the latest version.

## Error Message
```
Formatting failed: <input>:9: error: expected start of definition
    inline t match
           ^
```

## Example Code

```scala
enum T:
    case A
    case B

import T.*

class C {
  inline def get(using inline t: T): String =
    inline t match
      case A => "A"
      case B => "B"
}

@main
def main =
  inline given t: T = A
  val c = C()
  test(c.get, "A")
  test(c.get(using A), "A")
  test(c.get(using B), "B")

def test(actual: String, expected: String): Unit =
  println(actual)
  assert(actual == expected)
```

**Comment by vincenzobaz** [comment]
It seems to work [here](https://scastie.scala-lang.org/Psfs3scUS7mtF1tJpr8DhA)

**Comment by OlegYch** [comment]
@vincenzobaz fails in worksheet mode though
