### ISSUE TITLE
scalatest freespec does not compile under scala3 in scastie

### ISSUE THREAD

**Issue by scf37** [scalacenter/scastie#514]
https://scastie.scala-lang.org/KF3yVlD3SiWtlAo2CcHkbw

But compiles successfully for scala2

**Comment by vincenzobaz** [comment]
Version 3.2.8 of freespec does not support Scala 3 as you can see from the version matrix (https://index.scala-lang.org/artifacts/scalatest/scalatest).
However when I select freespec from the menu, version 3.2.8 is automatically selected and therefore `CrossVersion.for3Use2_13` is set and it is not removed when I change the version to 3.2.9

**Comment by vincenzobaz** [comment]
If I force 3.2.9 without crosscompile (https://scastie.scala-lang.org/sF7VyhmGRiC7XcTAx53M1g) the issues goes away.
I would say this bug is related to selecting the wrong version from Scaladex

**Comment by vincenzobaz** [comment]
Related to #392

**Comment by OlegYch** [comment]
related https://github.com/scalacenter/scaladex/issues/654

**Comment by vincenzobaz** [comment]
https://github.com/scalacenter/scastie/blob/9ab54dd632a7cddef830270ee403c0b6612e0194/api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala#L266
