### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by vincenzobaz** [scalacenter/scastie#517]
To get started https://github.com/scalacenter/scastie/search?q=autocomplete and #330

**Comment by hepin1989** [comment]
refs: https://github.com/scalacenter/scastie/issues/602 duplicated

**Comment by julienrf** [comment]
I think the best path forward would be to upgrade to CodeMirror 6, which does support LSP (see https://github.com/furqansoftware/codemirror-languageserver), which could communicate to the build server started by scastie. Any other idea?
