### ISSUE TITLE
Missing support for 3.0.2-RC1

### ISSUE THREAD

**Issue by aumann** [scalacenter/scastie#518]
Not sure if it's a valid use case: Having the current RC for the next version available would allow to quickly check whether certain compiler bugs are already fixed there (before opening an issue / the bolder venture of updating a larger sbt project).

As an aside: Is there already a policy in place w.r.t. when to drop "old" RC versions?

**Comment by vincenzobaz** [comment]
It seems a perfectly valid use case. As far as I know, enabling new compiler versions is done manually.
To support 3.0.2-RC1 you can modify https://github.com/scalacenter/scastie/blob/9ab54dd632a7cddef830270ee403c0b6612e0194/api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala#L14 
and eventually
https://github.com/scalacenter/scastie/blob/9ab54dd632a7cddef830270ee403c0b6612e0194/project/SbtShared.scala#L26
