### ISSUE TITLE
Save, Update, Fork & List

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#52]
For example in https://jsfiddle.net/

An anonymous user 

* [x] can save a snippet [/59eLudd3](https://jsfiddle.net/59eLudd3/)
* [x] anyone can update this resource [/59eLudd3/1](https://jsfiddle.net/59eLudd3/1/)
* [x] anyone can fork this resource [/h35oLtLc](https://jsfiddle.net/h35oLtLc/)

An authenticated user 

* [X] can save a resource [/MasseGuillaume/n93tzqv0](https://jsfiddle.net/MasseGuillaume/n93tzqv0/)
* [x] only this user can update this resource [/MasseGuillaume/n93tzqv0/1](https://jsfiddle.net/MasseGuillaume/n93tzqv0/1/)
* [x] anyone can fork this resource [/2eqfkLak](https://jsfiddle.net/2eqfkLak/)
* [x] can view all his resources `/MasseGuillaume`

Additions

* [x] we could also add an edit function where you would mutate the resource (for fixing bugs). (/MasseGuillaume/n93tzqv0 => mutates /MasseGuillaume/n93tzqv0)

**Comment by ShaneDelmore** [comment]
Another feature of scala-fiddle that would be useful here is being able to list saved programs.

**Comment by MasseGuillaume** [comment]
@ShaneDelmore good idea, I added `view all his resources` to the authenticated user section

**Comment by MasseGuillaume** [comment]
This is the shortest I can make the url: GGdknrcEQVu3elXyboKcYQ. It's a base64 of a UUID.

`https://scastie.scala-lang.org/MasseGuillaume/GGdknrcEQVu3elXyboKcYQ`
