### ISSUE TITLE
Escape should exit help dialogue

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scastie#53]
Seems I need to delete the help message with backspace

**Comment by MasseGuillaume** [comment]
Esc should delete the help message by default.

**Comment by MasseGuillaume** [comment]
Hum, cannot reproduce :S

**Comment by olafurpg** [comment]
I am able to reproduce the error in firefox and chrome but not safari. I suspect this has to do with me using vim-emulator browser extensions in chrome+firefox but no safari, but I find that a weird reason because I'm able to use the other hotkeys such as cmd+enter.

**Comment by MasseGuillaume** [comment]
Ok, I think I will close this since it looks it's based on your personal setup. You have the clear button if need be.

**Comment by olafurpg** [comment]
Yup was thinking the same.
