### ISSUE TITLE
Weird css for library search

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scastie#54]
The input field is smaller than wrapping box

<img width="775" alt="screen shot 2017-02-13 at 22 39 21" src="https://cloud.githubusercontent.com/assets/1408093/22904602/50e812ba-f23d-11e6-9a12-ba141593dd7f.png">
<img width="420" alt="screen shot 2017-02-13 at 22 39 25" src="https://cloud.githubusercontent.com/assets/1408093/22904606/51e64a06-f23d-11e6-8d7d-c563e6816b53.png">

**Comment by MasseGuillaume** [comment]
Can you give a capture of the full page ?

Ty ;-)

**Comment by olafurpg** [comment]
Is this OK?

<img width="1397" alt="screen shot 2017-02-15 at 19 35 52" src="https://cloud.githubusercontent.com/assets/1408093/22989530/864a4e3a-f3b6-11e6-9b75-71c6755eb1c2.png">

**Comment by MasseGuillaume** [comment]
Hehe they are equal size. It's an optical illusion.

**Comment by MasseGuillaume** [comment]
@olafurpg I'm still not shure what's the issue here.

**Comment by olafurpg** [comment]
There is now a darker background for the search input which makes it look a lot better

<img width="390" alt="screen shot 2017-02-24 at 12 05 40" src="https://cloud.githubusercontent.com/assets/1408093/23301330/aacd54a8-fa89-11e6-967d-33df7a3eeedf.png">

Fixed IMO!

**Comment by MasseGuillaume** [comment]
ahhhhhhhhhhhhhhhhhhhhhh now I get it lol. Man I'm color blind those things don't pop up in my face.
