### ISSUE TITLE
console output disappears immediately on mobile Android 

### ISSUE THREAD

**Issue by juhp** [scalacenter/scastie#540]
scastie seems pretty unusable on Android.

One sees output going to the console, but it all then disappears immediately.

**Comment by OlegYch** [comment]
@juhp seems to work fine for me on mobile firefox
can you show a sample scastie and a screenshot of wrong behavior?

**Comment by juhp** [comment]
Okay sure I can add a screenshot later.

I tested with both firefox and chrome: under Android 11 and 12.
Happy to provide any more details (versions etc) if it helps.

On desktop linux firefox it works well for me (though not in Chromium somehow).

**Comment by juhp** [comment]
![Screenshot_20211119-014519.png](https://user-images.githubusercontent.com/82731/142468879-319c7a0d-57a2-4d57-bf22-33fb701c10fa.png)

Simple screenshot of Android Firefox.
Eg just Running empty editor: 2-3 lines of any output flash past and then it's all gone. I could probably do screencast even - it would just be a second or two - very little to see.

This is Firefox 94.1.2 (Build #2015844587) on Android 12.

**Comment by OlegYch** [comment]
@juhp the sbt output is supposed to disappear
pretty sure it behaves the same way on desktop

**Comment by juhp** [comment]
You are right of course: seems it's my bad: looks I was using a bad/obsolete scastie path/hash apparently.

I tried now again directly from the site top URL and indeed `println("hi!")` now prints hi and an annotation appears in the editor buffer... So I think I need to be careful with the url I use.

**Comment by juhp** [comment]
I do just wonder if there might be any issue with scastie handling of stale/old worksheets?
But that is just a random thought/question I am putting out for the record.

**Comment by OlegYch** [comment]
@juhp could be, do you have the url?

**Comment by juhp** [comment]
I have this one in my android chrome url cache for example: https://scastie.scala-lang.org/kJ9W0dzGRFuTDf7q3tOojA

**Comment by OlegYch** [comment]
@juhp the url is supposed to change because we save the snippet each time you push the button
there is no output because `@main` is currently not recognized by scastie in worksheet mode, you can turn on off worksheet or use worksheet like this  https://scastie.scala-lang.org/XV37WalnTYiu5CzpQ59diA

**Comment by juhp** [comment]
Thank you very much for the clarification.

That does make sense.

**Comment by juhp** [comment]
We got that working now, great, thanks

Last question I hope!:
I guess there is no way to toggle Worksheet mode on mobile?

**Comment by OlegYch** [comment]
@juhp not in mobile view, but you can switch to desktop view in your browser
