### ISSUE TITLE
link to gitter

### ISSUE THREAD

**Issue by jimka2001** [scalacenter/scastie#546]
The tools has a link to the gitter page, which does not seem active.
Is this still active?  Where is the correct place to ask questions about scastie?
<img width="125" alt="68747470733a2f2f66696c65732e6769747465722e696d2f3538383634646334643733343038636534663435376230622f59696e492f7468756d622f53637265656e73686f742d323032322d30312d32332d61742d30302e33322e35322e706e67" src="https://user-images.githubusercontent.com/6414129/150659042-7b54f19b-88d4-43d0-8ddf-809818aa47c0.png">

**Comment by vincenzobaz** [comment]
Hello @jimka2001

You are right, Gitter is not very active. Yet we try to react to it during the week and we receive email notifications.
You can ask questions there or here in GItHub issues
