### ISSUE TITLE
Upgrade to JDK 17 final

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scastie#643]
happened to notice this today (at https://scastie.scala-lang.org/dWyBGp5SR3a9lrUm1v0ldQ):

```
 [info] welcome to sbt 1.7.1 (Oracle Corporation Java 17-ea)
```

note the "17-ea"

**Comment by rochala** [comment]
Fixed by https://github.com/scalacenter/scastie/pull/683/files#diff-5bc44c2c83b6b2f70747b7a2ecfed80bf78ee99023b5a8d4d7c7857217736204R115
