### ISSUE TITLE
Silent crash on `(x, implicit y => x`

### ISSUE THREAD

**Issue by Sporarum** [scalacenter/scastie#650]
Seems to run fine, but actually does not start

`(x, implicit y => x`

https://scastie.scala-lang.org/Sporarum/a3AOPPg2TmGhpjwxjxyrSA/84

this can be seen by adding a `println`:

https://scastie.scala-lang.org/Sporarum/a3AOPPg2TmGhpjwxjxyrSA/81

**Comment by Sporarum** [comment]
Update: even works on `(implicit y => x`

**Comment by Sporarum** [comment]
This might actually be a problem not specific to scastie

Given the future deprecation of `implicit`, I'll close this issue either way

**Comment by rochala** [comment]
The problem is with the unclosed parethesis. This is the reason for silent crash, not the implicits. Do you want to open new issue with that or should I ?

**Comment by Sporarum** [comment]
Oh, but shouldn't that notify the user instead of silently crashing ?

**Comment by rochala** [comment]
Yeah, I created issue for it.

**Comment by vincenzobaz** [comment]
Could it be an issue with the scalameta parser?

**Comment by rochala** [comment]
This is the issue with new scastie UI, I hid the errors which positions are higher than text length so we can't see the error.
