### ISSUE TITLE
Scastie page turns blank

### ISSUE THREAD

**Issue by Bersier** [scalacenter/scastie#652]
When entering the code below, the [whole page turns blank](https://scastie.scala-lang.org/eLkSFrAwQMKOF1PHnXVE6g) after evaluation:
```Scala
def foo(i: Int*): Int = i match
	case Nil => 0
	case h :: t => h + foo(t: _*)

foo(1, 2, 3)

```

**Comment by YorZ0** [comment]
I met the same problem when trying using spark :(

**Comment by bishabosha** [comment]
I reproduced this but for me at least it only happens on worksheet mode

**Comment by rochala** [comment]
I'm on it right now.
