### ISSUE TITLE
Help Needed for Tour Of Scala

### ISSUE THREAD

**Issue by leobenkel** [scalacenter/scastie#682]
Hello,

I am trying to update https://tourofscala.com after all the changes made in Scastie lately. But I am stuck. 
Here is the PR: https://github.com/leobenkel/tour-of-scala/pull/18 and the latest build: https://deploy-preview-18--tour-of-scala.netlify.app/scala/comparators 

As you can see, the Scastie side (right panel) is loading all broken. Lots of errors in the web JS console. 

If someone would like to pair with me on fixing this, it would be greatly appreciated. I would like to fully open source Tour of Scala (including content) but first I need to bring it back to a working version. 

I already shared small individual problems in https://github.com/scalacenter/scastie/issues/680 and https://github.com/scalacenter/scastie/issues/681 . But I think the issues are more systemic.

Thank you !

**Comment by rochala** [comment]
Hey, I'd be happy to help you resolve the issues and investigate the problem.
The broken UI in embedded Scastie is a known issue. I'll try to address it asap.
The JS errors, on the other hand, need further investigation. I'll try to take a look at it in the near future, probably Thursday or next week.

**Comment by leobenkel** [comment]
ok thanks! 
Let me know if you would like to live pair. I am pretty free this week during work hours (CET)
