### ISSUE TITLE
return of sxr

### ISSUE THREAD

**Issue by OlegYch** [scalacenter/scastie#69]
either via resurrected browse compiler plugin or a macro similar to the one used for worksheet
it greatly helps to see types of expressions and implicit expansions

**Comment by julienrf** [comment]
How do you imagine it? I don’t know if we can easily mix the edition mode with annotations produced by sxr.

**Comment by julienrf** [comment]
Or maybe that could be a read-only mode useful to show sxr-ed code along with its execution result. Then we could have an “edit” button that would bring us to the edition page.

**Comment by MasseGuillaume** [comment]
/cc @olafurpg could we do this with scalameta semantic api ?

for reference this is sxr: http://www.scala-sbt.org/0.13/sxr/sbt/Defaults.scala.html

**Comment by OlegYch** [comment]
@julienrf i think it could work as mouseover tooltips, once you start editing the code the edited positions get invalidated and have no mouseover

**Comment by olafurpg** [comment]
Once we have Symbol.tpe it should be possible to use the new meta mirror.
Symbol.members will also enable auto complete.

I can't say when it will be ready for this use case or promise how easy
it'll be to handle partially type checked trees like the presentation
compiler does. Rewrites for scalafix is currently the top priority.

**Comment by vincenzobaz** [comment]
[sxr is now unsupported](https://github.com/sbt/sxr)

**Comment by julienrf** [comment]
Is there any replacement we want to consider? Eg metadoc?

**Comment by olafurpg** [comment]
Alex is using Metadoc for Almond. The project would benefit from more love but it's a decent alternative to sxr.
