### ISSUE TITLE
Popup on hover does not look good and can’t be scrolled

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scastie#709]
![popup](https://user-images.githubusercontent.com/332812/212293188-21b2f0ca-6d64-4154-abeb-9dad8867e85c.gif)

- We see some overlapping between words in the content of the popup
- The popup disappears as soon as I move the mouse, making it impossible to scroll inside it, or just to select text, for instance

**Comment by rochala** [comment]
The reason of this issue is that hover is refreshed when we hover over the next letter. There should be something like "validFor" range which would disable subsequent displaying if the hover content still applies for the word
