### ISSUE TITLE
Completions look redundant

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scastie#711]
![redundant](https://user-images.githubusercontent.com/332812/212297936-ec062788-5cb2-4b45-9f72-62d8143c0038.gif)

What are the differences between those three options?

**Comment by tgodzik** [comment]
Those are named parameters, but not sure why they pop up in `*`, maybe a bug in Metals? Could you paste a snippet?

**Comment by julienrf** [comment]
Oh, I see, the second writes `x = `, and the last one writes `x = x`. I think those completions should not be proposed in this context. They should only be proposed if we pass an argument called `x`.

**Comment by tgodzik** [comment]
Looks like a Metals bug, we should not suggest those in case of infix expressions.

**Comment by rochala** [comment]
Closing it then.
