### ISSUE TITLE
Cannot see the full error on scastie-dev

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scastie#712]
On [scastie-dev](https://scastie-dev.scala-lang.org/srL1W1fzRleDIUmez5ypcA) I cannot see the full compilation error:

![image](https://user-images.githubusercontent.com/13123162/212299204-9760c678-54ca-4269-92d6-824b314f4b55.png)

On [scastie](https://scastie.scala-lang.org/veQn93CARXm804v676fd2A) I can:

![image](https://user-images.githubusercontent.com/13123162/212299382-5187f4bf-fc62-4c5e-97e0-fba555f4a32a.png)

**Comment by julienrf** [comment]
Is this fixed by #704?
