### ISSUE TITLE
Help dialog

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scastie#75]
- The CSS is not the same when it is shown the first time and when you evaluate `help` in the worksheet mode 
- The dialog do not show up again whereas I didn’t check the “don’t show again” box
- The “worksheet mode” section is empty

**Comment by MasseGuillaume** [comment]
> The CSS is not the same when it is shown the first time and when you evaluate help in the worksheet mode

solved #85

> The dialog do not show up again whereas I didn’t check the “don’t show again” box

solved c10691c409b2d9417ac1547d8dd56f0920fcf7fa

> The “worksheet mode” section is empty
