### ISSUE TITLE
Accessibility of scastie

### ISSUE THREAD

**Issue by jvican** [scalacenter/scastie#76]
Vimperator and similar tools build on the concept that you can browse a website by using keyboard shortcuts to scroll down pages, use input boxes, and links. However, when the evil Javascript comes into play, tools like Vimperator cannot recognize interactive parts of the website and hence fail.
  
In a nutshell, this means I cannot control Scastie just with my keyboard. I have to move my hand 20 cm away (often I don't have a keyboard) and get the mouse to click on the "Run" or "Libraries" button. Too much.
  
It would be awesome if Scastie defines those HTML links on the left menu so that the "on click" experience replicates the current JS behaviour.

**Comment by MasseGuillaume** [comment]
I changed the title to "Accessibility of scastie" since it reflects the issue in a more general form.

ARIA is a nice tool to deal with this: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA.

**Comment by MasseGuillaume** [comment]
@jvican without my mouse ;-)

![out](https://cloud.githubusercontent.com/assets/921490/25504069/767e5910-2b6a-11e7-9efa-4d4c153305e5.gif)

**Comment by jvican** [comment]
That is amazing :smile:.
