### ISSUE TITLE
Library selection is broken?

### ISSUE THREAD

**Issue by nemoo** [scalacenter/scastie#768]
### Describe the bug

Under Build settings > libraries, clicking a library of the list does not add it to the project

### To Reproduce

1. Go to Build settings > libraries,
2. Under libraries, write "cats"
3. With your mouse, click and double click "cats / core"

The cats library is not added to the project, in fact nothing changes in the UI at all.

### Expected behavior

The cats library should be added to the project

### Version

Scastie website

### What browsers are you seeing the problem on?

Chrome

**Comment by rochala** [comment]
The reason behind this issue is that `index.scala-lang.org` is down. But the issue is valid, it should work anyway, especially that completion list is working as intended.

**Comment by nemoo** [comment]
seems to work again now
