### ISSUE TITLE
sbt output is mixed with user output if running a snippet requires a build load on the backend

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scastie#806]
### Describe the bug

The output of sbt is included in the `userOutput` event stream when we try to run a snippet that requires a build load

### To Reproduce

Running any snippet whose configuration is different from the current configurations of the runners requires restarting a runner and loading the sbt configuration of that snippet in order to compile it properly.

Unfortunately, in such a situation we see in the “console” box the logs that come from sbt in addition to seeing the program output.

### Expected behavior

I can see some value in showing the sbt logs (users may diagnose issues in their snippet configuration thanks to those logs).

However, at the HTTP level, those logs should be exposed via a separate event stream than `userOutput` (e.g. `buildOutput`).

### Version

Scastie website

**Comment by rochala** [comment]
Event stream returns separate events for user output and sbt output, thus they can be filtered out. I don't think that this separation is necessary, as we can just filter by event type to separate outputs.

**Comment by julienrf** [comment]
I still see some sbt logs in the `userOutput` channel:

![Screenshot from 2023-06-01 10-38-09](https://github.com/scalacenter/scastie/assets/332812/eb5c4de8-27e2-4c27-9072-288f34a1ff43)

Could you please double check?

**Comment by rochala** [comment]
This is another issue, that we are not correctly separating sbt and user output. https://github.com/scalacenter/scastie/issues/865
