### ISSUE TITLE
Unclear on how to remove libraries

### ISSUE THREAD

**Issue by martijnhoekstra** [scalacenter/scastie#81]
I'm not clear on how to remove libraries once I've added them

**Comment by ShaneDelmore** [comment]
There is an X next to the library at the top of the list that will remove it.

**Comment by martijnhoekstra** [comment]
Hrm, I managed to break it so that doesn't show up. There are some breakages when there is no version for the scala version when changing the scala version after changing the library, but I'm unable to reproduce the exact failure I hit before now.
