### ISSUE TITLE
Can't find library in dropdown

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scastie#82]
Make it possible to add a library that somehow isn't found in the scaladex dropdown. For example, I can't for the life of me add Spark core to my scastie/paste/fiddle thing.

**Comment by MasseGuillaume** [comment]
You can add it in the `Sbt Configuration` section.

see https://scastie.scala-lang.org/2861

**Comment by MasseGuillaume** [comment]
spark core is available now. Let's track the issue in the Scaladex issue tracker: https://github.com/scalacenter/scaladex/issues/303

**Comment by MasseGuillaume** [comment]
Spark only has 2.11 and 2.10. It's now available.

![out](https://user-images.githubusercontent.com/921490/28369933-4937b4cc-6c99-11e7-95ea-6dfb386add23.gif)
