### ISSUE TITLE
Compilation failures gives message about worksheet mode

### ISSUE THREAD

**Issue by ShaneDelmore** [scalacenter/scastie#83]
Using Dotty in worksheet mode and pasting the following code
```scala
val answer: 42 = 42
```
results in the following compiler output

```
Connecting...
Connected.
[info] Compiling 1 Scala source to /tmp/scastie4278722253249209099/target/scala-2.11/classes...
[error] -- Error: /tmp/scastie4278722253249209099/src/main/scala/main.scala ------------
[error] 1 |val answer: 42 = 42
[error]   |^
[error]   |expected class or object definition
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 2 s, completed Feb 20, 2017 6:12:16 PM
```

Which seems reasonable but then prints this message in the worksheet:

```
You don't need a main method (or extends App) in Worksheet Mode
​```

Which is surprising because I did not create a main method or extend App.

**Comment by MasseGuillaume** [comment]
Hi @ShaneDelmore,

This issue is currently blocked by #102. I need a newer Scalameta version to parse this syntax. Right now, the program will not parse and you won't be able to use the Worksheet Mode. I'm closing this issue since I do not report wrongly that you need a `main method`.
