### ISSUE TITLE
Scastie isn't working currently

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scastie#840]
### Describe the bug

pressing Run does nothing

### Scastie snippet link

Scastie Editor Build Settings Dark Privacy Policy Help Up FeedbackLogin RunningNewFormat Clear Messages WorksheetDownloadEmbedMetals Status 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 enum Suit:   case Spade, Club, Diamond, Heart  enum Rank(val r: Int):   case Ace extends Rank(1)   case Two extends Rank(2)   case Three extends Rank(3)   case Four extends Rank(4)   case Five extends Rank(5)   case Six extends Rank(6)   case Seven extends Rank(7)   case Eight extends Rank(8)   case Nine extends Rank(9)   case Ten extends Rank(10)   case Jack extends Rank(11)   case Queen extends Rank(12)   case King extends Rank(13)  case class PlayingCard(suit: Suit, rank: Rank)  val deck = for {   suit <- Suit.values   rank <- Rank.values } yield PlayingCard(suit, rank)  deck.foreach { pc => println(pc)} Console (F3) scastie: Sending task to the server.

### To Reproduce

go to any scastie, press Run. the console says "scastie: Sending task to the server." and hangs there

### Expected behavior

normal operation

### Screenshot ( Optional )

<img width="1722" alt="Screenshot 2023-05-10 at 1 15 21 PM" src="https://github.com/scalacenter/scastie/assets/161079/0b4bca56-7d4e-4ac3-bfa1-a960a5ede0fc">

### Version

Scastie website

### What browsers are you seeing the problem on?

Safari

### Relevant log output

```
scastie: Sending task to the server. 
```

**Comment by rochala** [comment]
It is working now, thank you for reporting. I'll investigate the issue first thing in the morning.

**Comment by SethTisue** [comment]
is there any further information we should record here before closing the ticket?

**Comment by rochala** [comment]
The issue was the server run out of disk space. At the moment Scastie still has some stability issues especially with metals runner. I'm going to do release tomorrow with way higher resources which will probably fix the issue. As the underlying problem was solved I'm closing this.
