### ISSUE TITLE
Feature Idea: Cached output.

### ISSUE THREAD

**Issue by ShaneDelmore** [scalacenter/scastie#86]
I believe a common use case for scastie is to demonstrate usage of code or a technique.  For viewers of the url it would be nice to immediately see the output I am sending them too without the need for sbt to spin up and compile with any included libs.  This also could save resources on the server side as I believe that often when I send an example the person viewing it only reads it, and less often edits it.  Even when they do edit, they will likely be reading it to comprehend before editing it to experiment so displaying the output immediately while spinning up the compiler in the background could still be useful.

**Comment by MasseGuillaume** [comment]
We do this already :-). If you save a resource and share the url the cached output will be served.

**Comment by heathermiller** [comment]
Are you sure it works in worksheet mode though, @masseguillaume? I noticed the same thing Shane did, but on worksheets; I've had to re-evaluate worksheets because the results weren't cached.

**Comment by OlegYch** [comment]
there is definitely something wonky going on when loading a saved paste
in both worksheet and simple mode the output is lost

**Comment by MasseGuillaume** [comment]
@ShaneDelmore

I just update the sharing model. It should be cached by default.

https://scastie.scala-lang.org/MasseGuillaume/u1N92ngURXuIltTaz6CnUw/0
