### ISSUE TITLE
Scala-lang.org Scala.js snippet is broken

### ISSUE THREAD

**Issue by keynmol** [scalacenter/scastie#873]
### Describe the bug

The Scala.js snippet on the Scala-lang.org website no longer works in scastie: https://scastie.scala-lang.org/9A0WyPS2T5SgmIGi0jE46w

### Scastie snippet link

https://scastie.scala-lang.org/9A0WyPS2T5SgmIGi0jE46w

### To Reproduce

1. Go to https://scastie.scala-lang.org/9A0WyPS2T5SgmIGi0jE46w
2. Build
3. Observe failure (as on the screenshot)

### Expected behavior

Code builds

### Screenshot ( Optional )

![image](https://github.com/scalacenter/scastie/assets/1052965/4d9781fb-ec4f-4294-a19b-c06f48fdc45b)

### Version

Scastie website

**Comment by rochala** [comment]
Thanks for reporting. I'm going to hotfix it for now by replacing the link to the working one, but in the future it would be better to have a user snippet instead of anonymous one, but to do it I have to change few things in Scastie.
