### ISSUE TITLE
"Github issues" button does not lead to a issue-form or an issue-form slections screen

### ISSUE THREAD

**Issue by Sporarum** [scalacenter/scastie#889]
The button links to 
https://github.com/scalacenter/scastie/issues/new

Whereas the "new issue" button in github lead to:
https://github.com/scalacenter/scastie/issues/new/choose

And as you can see, this allows me to completely ignore forms, which since they are meant to guide the user, is a bad thing

**Comment by rochala** [comment]
Hey, do you mean the `New issue` button in the Issue tab ? If so, I think this is expected. There are some issues that don't fall into the bug report tab, so a user can always create a custom one to meet their requirements.

**Comment by Sporarum** [comment]
Yes, that one !

I think it would be better to add a "custom" option to .../next/choose, because the template is really helpful in creating a bug report, and it would be a shame if people miss it

**Comment by rochala** [comment]
I don't think I understand the issue here. There is a bug report template present which is indeed created to guide people and there is a custom option available behind the `Don’t see your issue here? Open a blank issue.`.

**Comment by Sporarum** [comment]
Ah I did not notice this,
but then it makes even more sense that the "Feedback"/"Github issue" button should link to `.../next/choose`

**Comment by rochala** [comment]
Ahh you're talking about the button on the website ! Ok I got it :D

**Comment by Sporarum** [comment]
Oh right sorry, should have been more clear in the initial report !

**Comment by Sporarum** [comment]
I just tried it out, and it still lead me to `.../issues/new` instead of `.../issues/new/choose`, is this expected ?
