### ISSUE TITLE
There's no scroll on first welcome page

### ISSUE THREAD

**Issue by vascorsd** [scalacenter/scastie#89]
Hello, quickly wanted to try this and going to the site, after github login, when you reach the welcome page the content is too big to fit on the screen but the page doesn't have any scrollbar so, the mouse scroll doesn't work nor do I have a scrollbar to actually use.

If I click on a blank place on the page then I can use the arrow keys UP and DOWN to see the remaining two menu icons and the content below the "Build Info".

Screenshot of how it looks
![weird_screenshot](https://cloud.githubusercontent.com/assets/13673/23145739/87204948-f7c8-11e6-9867-8c9e2c37c367.png)

Seems it is an issue around other sections when choosing from the menu other item.

Sytem Info:
  * Firefox 51
  * Linux
  * Monitor resolution: 1366x768

**Comment by MasseGuillaume** [comment]
Thanks !
