### ISSUE TITLE
Can't define an AnyVal class in worksheet mode

### ISSUE THREAD

**Issue by densh** [scalacenter/scastie#91]
https://scastie.scala-lang.org/3639

**Comment by julienrf** [comment]
What would you expect?

There are two evaluation modes: worksheet and “program”. In worksheet mode you can not define value classes but can write non-top-level definitions (in your case, the last two lines would be valid). In program mode you can only write top-level definitions (so, in your case, the last two lines would be rejected).

**Comment by densh** [comment]
I'd expect it to work regardless of the mode. If you can define normal classes, there is no reason apart from implementation details why value classes shouldn't work too.

**Comment by julienrf** [comment]
I agree that it would be nice if value classes worked in worksheet mode. They do work in program mode, so I renamed your issue.

**Comment by MasseGuillaume** [comment]
this is doable, we need to extract value classes outside the instrumenting class preserving the line position (to shit error messages).

**Comment by MasseGuillaume** [comment]
related: #80
