### ISSUE TITLE
Tab inserts a tab character, but autoformat produces spaces

### ISSUE THREAD

**Issue by rmgk** [scalacenter/scastie#967]
### Describe the bug

indentation by pressing tab and by using autoformat is inconsistent

### Scastie snippet link

https://scastie.scala-lang.org/esGBxPTUQ2O9ZSL2Z8byyw

### To Reproduce

press the format button: it removes the tab
try to use the tab key to indent the second println: insersts a tab (and produces the above compiler error)

### Expected behavior

autoformat and tab key should use the same character(s) for indentation

there is https://github.com/scalacenter/scastie/issues/444 which implies that tab should insert 2 space characters, but I don’t see that happen, at least not on firefox (wayland) and chrome (xwayland).

### Version

Scastie website

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by mwisnicki** [comment]
Default formatting is also broken on Windows/Chrome. Makes usage with Scala 3 super annoying since nothing compiles as written unless I manually adjust indentation.

**Comment by rochala** [comment]
I'll work on this tomorrow, unless maybe you want to give it at try ?
