### ISSUE TITLE
Scastie isn't working, currently, nor for at least two days.

### ISSUE THREAD

**Issue by davesmith00000** [scalacenter/scastie#986]
### Describe the bug

The "I'm compiling" spinner spins, but nothing happens.

### Scastie snippet link

val x = 10

### To Reproduce

Go to the site
Enter some code
Hit run
Wait for output.

### Expected behavior

For the output to arrive.

### Screenshot ( Optional )

![image](https://github.com/scalacenter/scastie/assets/908709/b4cf7ac3-6dfa-4875-b3cb-17f7b97807d9)

### Version

Scastie website

### What browsers are you seeing the problem on?

Chrome

**Comment by rochala** [comment]
It is fixed, thanks for reporting :D
